export interface CelestialCoordinates {
  galaxy: number;
  sector: number;
  system: number;
  orbit: number;
  index: number;
}

export interface CelestialBody {
  id: string;
  name: string;
  type: 'star' | 'planet' | 'dwarf_planet' | 'moon' | 'asteroid' | 'comet';
  parentId: string | null;
  coordinates: CelestialCoordinates;
  coordinateString: string;
  properties: {
    mass?: number;
    radius?: number;
    orbitalPeriod?: number;
    rotationPeriod?: number;
    distanceFromParent?: number;
    surfaceGravity?: number;
    meanTemperature?: number;
    atmosphere?: string[];
    composition?: string[];
    rings?: boolean;
    habitable?: boolean;
    description?: string;
  };
}

export interface StarSystem {
  id: string;
  name: string;
  coordinates: CelestialCoordinates;
  coordinateString: string;
  starType: string;
  bodies: CelestialBody[];
}

export interface Galaxy {
  id: string;
  name: string;
  type: 'spiral' | 'elliptical' | 'irregular' | 'lenticular';
  size: 'dwarf' | 'small' | 'medium' | 'large' | 'giant';
  starCount: number;
  diameter: number;
  coordinates: { x: number; y: number; z: number };
}

export function formatCoordinates(coords: CelestialCoordinates): string {
  return `${coords.galaxy}:${coords.sector}:${coords.system}:${coords.orbit}:${coords.index}`;
}

export function parseCoordinates(coordString: string): CelestialCoordinates {
  const parts = coordString.split(':').map(Number);
  return {
    galaxy: parts[0] || 0,
    sector: parts[1] || 0,
    system: parts[2] || 0,
    orbit: parts[3] || 0,
    index: parts[4] || 0,
  };
}

export const SOL_SYSTEM: StarSystem = {
  id: 'sol',
  name: 'Sol System',
  coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 0, index: 0 },
  coordinateString: '0:0:0:0:0',
  starType: 'G2V',
  bodies: [
    {
      id: 'sol-sun',
      name: 'Sol',
      type: 'star',
      parentId: null,
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 0, index: 0 },
      coordinateString: '0:0:0:0:0',
      properties: {
        mass: 1.989e30,
        radius: 696340,
        rotationPeriod: 25.05,
        surfaceGravity: 274,
        meanTemperature: 5778,
        composition: ['Hydrogen (73%)', 'Helium (25%)', 'Oxygen', 'Carbon', 'Iron'],
        description: 'Yellow dwarf star at the center of our solar system. Type G2V main-sequence star.',
      },
    },
    {
      id: 'sol-mercury',
      name: 'Mercury',
      type: 'planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 1, index: 0 },
      coordinateString: '0:0:0:1:0',
      properties: {
        mass: 3.285e23,
        radius: 2439.7,
        orbitalPeriod: 88,
        rotationPeriod: 58.646,
        distanceFromParent: 57.9,
        surfaceGravity: 3.7,
        meanTemperature: 440,
        atmosphere: [],
        composition: ['Iron', 'Silicate'],
        habitable: false,
        description: 'Smallest planet and closest to the Sun. Heavily cratered surface with extreme temperature variations.',
      },
    },
    {
      id: 'sol-venus',
      name: 'Venus',
      type: 'planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 2, index: 0 },
      coordinateString: '0:0:0:2:0',
      properties: {
        mass: 4.867e24,
        radius: 6051.8,
        orbitalPeriod: 224.7,
        rotationPeriod: 243.025,
        distanceFromParent: 108.2,
        surfaceGravity: 8.87,
        meanTemperature: 737,
        atmosphere: ['Carbon Dioxide (96.5%)', 'Nitrogen (3.5%)', 'Sulfur Dioxide'],
        composition: ['Silicate', 'Iron'],
        habitable: false,
        description: 'Second planet from the Sun. Dense atmosphere creates extreme greenhouse effect. Rotates retrograde.',
      },
    },
    {
      id: 'sol-earth',
      name: 'Earth',
      type: 'planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 3, index: 0 },
      coordinateString: '0:0:0:3:0',
      properties: {
        mass: 5.972e24,
        radius: 6371,
        orbitalPeriod: 365.25,
        rotationPeriod: 0.997,
        distanceFromParent: 149.6,
        surfaceGravity: 9.81,
        meanTemperature: 288,
        atmosphere: ['Nitrogen (78%)', 'Oxygen (21%)', 'Argon (0.9%)', 'Carbon Dioxide'],
        composition: ['Iron', 'Oxygen', 'Silicon', 'Magnesium'],
        habitable: true,
        description: 'Third planet from the Sun. Only known planet to harbor life. 71% covered by water.',
      },
    },
    {
      id: 'sol-luna',
      name: 'Luna',
      type: 'moon',
      parentId: 'sol-earth',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 3, index: 1 },
      coordinateString: '0:0:0:3:1',
      properties: {
        mass: 7.342e22,
        radius: 1737.4,
        orbitalPeriod: 27.3,
        rotationPeriod: 27.3,
        distanceFromParent: 0.384,
        surfaceGravity: 1.62,
        meanTemperature: 250,
        atmosphere: [],
        composition: ['Oxygen', 'Silicon', 'Magnesium', 'Iron', 'Calcium'],
        habitable: false,
        description: "Earth's only natural satellite. Tidally locked. Fifth largest moon in the Solar System.",
      },
    },
    {
      id: 'sol-mars',
      name: 'Mars',
      type: 'planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 4, index: 0 },
      coordinateString: '0:0:0:4:0',
      properties: {
        mass: 6.39e23,
        radius: 3389.5,
        orbitalPeriod: 687,
        rotationPeriod: 1.026,
        distanceFromParent: 227.9,
        surfaceGravity: 3.71,
        meanTemperature: 210,
        atmosphere: ['Carbon Dioxide (95%)', 'Nitrogen (2.7%)', 'Argon (1.6%)'],
        composition: ['Iron', 'Silicon', 'Oxygen'],
        habitable: false,
        description: 'Fourth planet. Known as the Red Planet. Home to Olympus Mons, the largest volcano in the Solar System.',
      },
    },
    {
      id: 'sol-phobos',
      name: 'Phobos',
      type: 'moon',
      parentId: 'sol-mars',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 4, index: 1 },
      coordinateString: '0:0:0:4:1',
      properties: {
        mass: 1.0659e16,
        radius: 11.267,
        orbitalPeriod: 0.319,
        distanceFromParent: 0.00942,
        surfaceGravity: 0.0057,
        meanTemperature: 233,
        atmosphere: [],
        composition: ['Carbon', 'Silicon'],
        habitable: false,
        description: 'Larger and innermost of Mars\' two moons. Irregularly shaped, heavily cratered.',
      },
    },
    {
      id: 'sol-deimos',
      name: 'Deimos',
      type: 'moon',
      parentId: 'sol-mars',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 4, index: 2 },
      coordinateString: '0:0:0:4:2',
      properties: {
        mass: 1.4762e15,
        radius: 6.2,
        orbitalPeriod: 1.263,
        distanceFromParent: 0.02346,
        surfaceGravity: 0.003,
        meanTemperature: 233,
        atmosphere: [],
        composition: ['Carbon', 'Silicon'],
        habitable: false,
        description: 'Smaller and outermost moon of Mars. Smooth surface due to regolith.',
      },
    },
    {
      id: 'sol-ceres',
      name: 'Ceres',
      type: 'dwarf_planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 5, index: 0 },
      coordinateString: '0:0:0:5:0',
      properties: {
        mass: 9.393e20,
        radius: 473,
        orbitalPeriod: 1682,
        rotationPeriod: 0.378,
        distanceFromParent: 413.7,
        surfaceGravity: 0.28,
        meanTemperature: 168,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Largest object in the asteroid belt. Classified as a dwarf planet. Contains water ice.',
      },
    },
    {
      id: 'sol-jupiter',
      name: 'Jupiter',
      type: 'planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 6, index: 0 },
      coordinateString: '0:0:0:6:0',
      properties: {
        mass: 1.898e27,
        radius: 69911,
        orbitalPeriod: 4333,
        rotationPeriod: 0.414,
        distanceFromParent: 778.5,
        surfaceGravity: 24.79,
        meanTemperature: 165,
        atmosphere: ['Hydrogen (89%)', 'Helium (10%)', 'Methane', 'Ammonia'],
        composition: ['Hydrogen', 'Helium'],
        rings: true,
        habitable: false,
        description: 'Largest planet in the Solar System. Gas giant with iconic Great Red Spot storm.',
      },
    },
    {
      id: 'sol-io',
      name: 'Io',
      type: 'moon',
      parentId: 'sol-jupiter',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 6, index: 1 },
      coordinateString: '0:0:0:6:1',
      properties: {
        mass: 8.931e22,
        radius: 1821.6,
        orbitalPeriod: 1.769,
        distanceFromParent: 0.422,
        surfaceGravity: 1.796,
        meanTemperature: 110,
        atmosphere: ['Sulfur Dioxide'],
        composition: ['Silicate', 'Sulfur', 'Iron'],
        habitable: false,
        description: 'Most volcanically active body in the Solar System. Innermost Galilean moon.',
      },
    },
    {
      id: 'sol-europa',
      name: 'Europa',
      type: 'moon',
      parentId: 'sol-jupiter',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 6, index: 2 },
      coordinateString: '0:0:0:6:2',
      properties: {
        mass: 4.8e22,
        radius: 1560.8,
        orbitalPeriod: 3.551,
        distanceFromParent: 0.671,
        surfaceGravity: 1.314,
        meanTemperature: 102,
        atmosphere: ['Oxygen (trace)'],
        composition: ['Water Ice', 'Silicate'],
        habitable: false,
        description: 'Smooth ice surface with subsurface ocean. Prime candidate for extraterrestrial life.',
      },
    },
    {
      id: 'sol-ganymede',
      name: 'Ganymede',
      type: 'moon',
      parentId: 'sol-jupiter',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 6, index: 3 },
      coordinateString: '0:0:0:6:3',
      properties: {
        mass: 1.4819e23,
        radius: 2634.1,
        orbitalPeriod: 7.155,
        distanceFromParent: 1.07,
        surfaceGravity: 1.428,
        meanTemperature: 110,
        atmosphere: ['Oxygen (trace)'],
        composition: ['Water Ice', 'Silicate'],
        habitable: false,
        description: 'Largest moon in the Solar System. Larger than Mercury. Has its own magnetic field.',
      },
    },
    {
      id: 'sol-callisto',
      name: 'Callisto',
      type: 'moon',
      parentId: 'sol-jupiter',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 6, index: 4 },
      coordinateString: '0:0:0:6:4',
      properties: {
        mass: 1.0759e23,
        radius: 2410.3,
        orbitalPeriod: 16.689,
        distanceFromParent: 1.883,
        surfaceGravity: 1.235,
        meanTemperature: 134,
        atmosphere: ['Carbon Dioxide (trace)'],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Most heavily cratered object in the Solar System. Possible subsurface ocean.',
      },
    },
    {
      id: 'sol-saturn',
      name: 'Saturn',
      type: 'planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 7, index: 0 },
      coordinateString: '0:0:0:7:0',
      properties: {
        mass: 5.683e26,
        radius: 58232,
        orbitalPeriod: 10759,
        rotationPeriod: 0.444,
        distanceFromParent: 1432,
        surfaceGravity: 10.44,
        meanTemperature: 134,
        atmosphere: ['Hydrogen (96%)', 'Helium (3%)', 'Methane', 'Ammonia'],
        composition: ['Hydrogen', 'Helium'],
        rings: true,
        habitable: false,
        description: 'Second largest planet. Famous for extensive ring system. Least dense planet - would float on water.',
      },
    },
    {
      id: 'sol-titan',
      name: 'Titan',
      type: 'moon',
      parentId: 'sol-saturn',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 7, index: 1 },
      coordinateString: '0:0:0:7:1',
      properties: {
        mass: 1.3452e23,
        radius: 2574.7,
        orbitalPeriod: 15.945,
        distanceFromParent: 1.222,
        surfaceGravity: 1.352,
        meanTemperature: 94,
        atmosphere: ['Nitrogen (98%)', 'Methane (2%)'],
        composition: ['Water Ice', 'Rock', 'Hydrocarbons'],
        habitable: false,
        description: 'Only moon with a dense atmosphere. Has liquid methane lakes. Largest moon of Saturn.',
      },
    },
    {
      id: 'sol-enceladus',
      name: 'Enceladus',
      type: 'moon',
      parentId: 'sol-saturn',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 7, index: 2 },
      coordinateString: '0:0:0:7:2',
      properties: {
        mass: 1.08e20,
        radius: 252.1,
        orbitalPeriod: 1.37,
        distanceFromParent: 0.238,
        surfaceGravity: 0.113,
        meanTemperature: 75,
        atmosphere: ['Water Vapor (trace)'],
        composition: ['Water Ice', 'Silicate'],
        habitable: false,
        description: 'Active cryovolcanism with water geysers. Subsurface ocean. Prime astrobiology target.',
      },
    },
    {
      id: 'sol-rhea',
      name: 'Rhea',
      type: 'moon',
      parentId: 'sol-saturn',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 7, index: 3 },
      coordinateString: '0:0:0:7:3',
      properties: {
        mass: 2.306e21,
        radius: 763.8,
        orbitalPeriod: 4.518,
        distanceFromParent: 0.527,
        surfaceGravity: 0.264,
        meanTemperature: 76,
        atmosphere: ['Oxygen (trace)', 'Carbon Dioxide (trace)'],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Second largest moon of Saturn. Heavily cratered icy surface.',
      },
    },
    {
      id: 'sol-iapetus',
      name: 'Iapetus',
      type: 'moon',
      parentId: 'sol-saturn',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 7, index: 4 },
      coordinateString: '0:0:0:7:4',
      properties: {
        mass: 1.805e21,
        radius: 734.5,
        orbitalPeriod: 79.32,
        distanceFromParent: 3.561,
        surfaceGravity: 0.223,
        meanTemperature: 130,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Two-toned moon with bright and dark hemispheres. Equatorial ridge up to 20km high.',
      },
    },
    {
      id: 'sol-dione',
      name: 'Dione',
      type: 'moon',
      parentId: 'sol-saturn',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 7, index: 5 },
      coordinateString: '0:0:0:7:5',
      properties: {
        mass: 1.095e21,
        radius: 561.4,
        orbitalPeriod: 2.737,
        distanceFromParent: 0.377,
        surfaceGravity: 0.232,
        meanTemperature: 87,
        atmosphere: ['Oxygen (trace)'],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Fourth largest moon of Saturn. Bright ice cliffs called "wispy terrain".',
      },
    },
    {
      id: 'sol-tethys',
      name: 'Tethys',
      type: 'moon',
      parentId: 'sol-saturn',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 7, index: 6 },
      coordinateString: '0:0:0:7:6',
      properties: {
        mass: 6.174e20,
        radius: 531.1,
        orbitalPeriod: 1.888,
        distanceFromParent: 0.295,
        surfaceGravity: 0.146,
        meanTemperature: 86,
        atmosphere: [],
        composition: ['Water Ice'],
        habitable: false,
        description: 'Nearly pure water ice. Features massive Odysseus crater and Ithaca Chasma canyon.',
      },
    },
    {
      id: 'sol-mimas',
      name: 'Mimas',
      type: 'moon',
      parentId: 'sol-saturn',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 7, index: 7 },
      coordinateString: '0:0:0:7:7',
      properties: {
        mass: 3.749e19,
        radius: 198.2,
        orbitalPeriod: 0.942,
        distanceFromParent: 0.186,
        surfaceGravity: 0.064,
        meanTemperature: 64,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Smallest astronomical body known to be in hydrostatic equilibrium. "Death Star" appearance.',
      },
    },
    {
      id: 'sol-uranus',
      name: 'Uranus',
      type: 'planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 8, index: 0 },
      coordinateString: '0:0:0:8:0',
      properties: {
        mass: 8.681e25,
        radius: 25362,
        orbitalPeriod: 30687,
        rotationPeriod: 0.718,
        distanceFromParent: 2867,
        surfaceGravity: 8.69,
        meanTemperature: 76,
        atmosphere: ['Hydrogen (83%)', 'Helium (15%)', 'Methane (2%)'],
        composition: ['Water', 'Methane', 'Ammonia'],
        rings: true,
        habitable: false,
        description: 'Ice giant tilted 98 degrees on its side. Coldest planetary atmosphere. 27 known moons.',
      },
    },
    {
      id: 'sol-titania',
      name: 'Titania',
      type: 'moon',
      parentId: 'sol-uranus',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 8, index: 1 },
      coordinateString: '0:0:0:8:1',
      properties: {
        mass: 3.527e21,
        radius: 788.4,
        orbitalPeriod: 8.706,
        distanceFromParent: 0.436,
        surfaceGravity: 0.379,
        meanTemperature: 70,
        atmosphere: ['Carbon Dioxide (trace)'],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Largest moon of Uranus. Named after the fairy queen in A Midsummer Night\'s Dream.',
      },
    },
    {
      id: 'sol-oberon',
      name: 'Oberon',
      type: 'moon',
      parentId: 'sol-uranus',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 8, index: 2 },
      coordinateString: '0:0:0:8:2',
      properties: {
        mass: 3.014e21,
        radius: 761.4,
        orbitalPeriod: 13.463,
        distanceFromParent: 0.584,
        surfaceGravity: 0.346,
        meanTemperature: 75,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Outermost major moon of Uranus. Dark surface with large craters.',
      },
    },
    {
      id: 'sol-umbriel',
      name: 'Umbriel',
      type: 'moon',
      parentId: 'sol-uranus',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 8, index: 3 },
      coordinateString: '0:0:0:8:3',
      properties: {
        mass: 1.172e21,
        radius: 584.7,
        orbitalPeriod: 4.144,
        distanceFromParent: 0.266,
        surfaceGravity: 0.23,
        meanTemperature: 75,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Darkest of the large Uranian moons. Ancient, heavily cratered surface.',
      },
    },
    {
      id: 'sol-ariel',
      name: 'Ariel',
      type: 'moon',
      parentId: 'sol-uranus',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 8, index: 4 },
      coordinateString: '0:0:0:8:4',
      properties: {
        mass: 1.353e21,
        radius: 578.9,
        orbitalPeriod: 2.52,
        distanceFromParent: 0.191,
        surfaceGravity: 0.269,
        meanTemperature: 60,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Fourth-largest moon of Uranus. Brightest of the Uranian moons.',
      },
    },
    {
      id: 'sol-miranda',
      name: 'Miranda',
      type: 'moon',
      parentId: 'sol-uranus',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 8, index: 5 },
      coordinateString: '0:0:0:8:5',
      properties: {
        mass: 6.59e19,
        radius: 235.8,
        orbitalPeriod: 1.413,
        distanceFromParent: 0.129,
        surfaceGravity: 0.079,
        meanTemperature: 60,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Smallest and innermost major moon. Extremely varied terrain with Verona Rupes cliff.',
      },
    },
    {
      id: 'sol-neptune',
      name: 'Neptune',
      type: 'planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 9, index: 0 },
      coordinateString: '0:0:0:9:0',
      properties: {
        mass: 1.024e26,
        radius: 24622,
        orbitalPeriod: 60190,
        rotationPeriod: 0.671,
        distanceFromParent: 4515,
        surfaceGravity: 11.15,
        meanTemperature: 72,
        atmosphere: ['Hydrogen (80%)', 'Helium (19%)', 'Methane (1%)'],
        composition: ['Water', 'Methane', 'Ammonia'],
        rings: true,
        habitable: false,
        description: 'Most distant planet. Strongest sustained winds in the Solar System. Deep blue color from methane.',
      },
    },
    {
      id: 'sol-triton',
      name: 'Triton',
      type: 'moon',
      parentId: 'sol-neptune',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 9, index: 1 },
      coordinateString: '0:0:0:9:1',
      properties: {
        mass: 2.14e22,
        radius: 1353.4,
        orbitalPeriod: 5.877,
        distanceFromParent: 0.355,
        surfaceGravity: 0.779,
        meanTemperature: 38,
        atmosphere: ['Nitrogen (trace)', 'Methane (trace)'],
        composition: ['Nitrogen Ice', 'Water Ice', 'Rock'],
        habitable: false,
        description: 'Largest moon of Neptune. Retrograde orbit suggests captured Kuiper belt object. Active geysers.',
      },
    },
    {
      id: 'sol-nereid',
      name: 'Nereid',
      type: 'moon',
      parentId: 'sol-neptune',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 9, index: 2 },
      coordinateString: '0:0:0:9:2',
      properties: {
        mass: 3.1e19,
        radius: 170,
        orbitalPeriod: 360.14,
        distanceFromParent: 5.513,
        surfaceGravity: 0.071,
        meanTemperature: 50,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Third-largest moon of Neptune. Most eccentric orbit of any moon.',
      },
    },
    {
      id: 'sol-proteus',
      name: 'Proteus',
      type: 'moon',
      parentId: 'sol-neptune',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 9, index: 3 },
      coordinateString: '0:0:0:9:3',
      properties: {
        mass: 4.4e19,
        radius: 210,
        orbitalPeriod: 1.122,
        distanceFromParent: 0.118,
        surfaceGravity: 0.07,
        meanTemperature: 51,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Second-largest moon of Neptune. Largest irregularly shaped moon in the Solar System.',
      },
    },
    {
      id: 'sol-pluto',
      name: 'Pluto',
      type: 'dwarf_planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 10, index: 0 },
      coordinateString: '0:0:0:10:0',
      properties: {
        mass: 1.303e22,
        radius: 1188.3,
        orbitalPeriod: 90560,
        rotationPeriod: 6.387,
        distanceFromParent: 5906.4,
        surfaceGravity: 0.62,
        meanTemperature: 44,
        atmosphere: ['Nitrogen', 'Methane', 'Carbon Monoxide'],
        composition: ['Nitrogen Ice', 'Water Ice', 'Rock'],
        habitable: false,
        description: 'Largest known dwarf planet in the Kuiper belt. Heart-shaped nitrogen ice glacier.',
      },
    },
    {
      id: 'sol-charon',
      name: 'Charon',
      type: 'moon',
      parentId: 'sol-pluto',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 10, index: 1 },
      coordinateString: '0:0:0:10:1',
      properties: {
        mass: 1.586e21,
        radius: 606,
        orbitalPeriod: 6.387,
        distanceFromParent: 0.0196,
        surfaceGravity: 0.288,
        meanTemperature: 53,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Largest moon of Pluto. Mutually tidally locked with Pluto. Forms a binary system.',
      },
    },
    {
      id: 'sol-eris',
      name: 'Eris',
      type: 'dwarf_planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 11, index: 0 },
      coordinateString: '0:0:0:11:0',
      properties: {
        mass: 1.66e22,
        radius: 1163,
        orbitalPeriod: 203830,
        rotationPeriod: 25.9,
        distanceFromParent: 10125,
        surfaceGravity: 0.82,
        meanTemperature: 30,
        atmosphere: ['Nitrogen (trace)', 'Methane (trace)'],
        composition: ['Nitrogen Ice', 'Methane Ice', 'Rock'],
        habitable: false,
        description: 'Most massive dwarf planet. Located in scattered disc. Discovery led to Pluto\'s reclassification.',
      },
    },
    {
      id: 'sol-dysnomia',
      name: 'Dysnomia',
      type: 'moon',
      parentId: 'sol-eris',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 11, index: 1 },
      coordinateString: '0:0:0:11:1',
      properties: {
        mass: 8.2e19,
        radius: 350,
        orbitalPeriod: 15.774,
        distanceFromParent: 0.0373,
        surfaceGravity: 0.045,
        meanTemperature: 30,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Only known moon of Eris. Named after the Greek goddess of lawlessness.',
      },
    },
    {
      id: 'sol-makemake',
      name: 'Makemake',
      type: 'dwarf_planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 12, index: 0 },
      coordinateString: '0:0:0:12:0',
      properties: {
        mass: 3.1e21,
        radius: 715,
        orbitalPeriod: 111845,
        rotationPeriod: 22.48,
        distanceFromParent: 6850,
        surfaceGravity: 0.4,
        meanTemperature: 32,
        atmosphere: [],
        composition: ['Nitrogen Ice', 'Methane Ice', 'Ethane'],
        habitable: false,
        description: 'Second-brightest Kuiper belt object. Reddish-brown color. Very low density atmosphere.',
      },
    },
    {
      id: 'sol-haumea',
      name: 'Haumea',
      type: 'dwarf_planet',
      parentId: 'sol-sun',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 13, index: 0 },
      coordinateString: '0:0:0:13:0',
      properties: {
        mass: 4.006e21,
        radius: 816,
        orbitalPeriod: 103774,
        rotationPeriod: 3.9155,
        distanceFromParent: 6452,
        surfaceGravity: 0.401,
        meanTemperature: 32,
        atmosphere: [],
        composition: ['Water Ice', 'Rock'],
        rings: true,
        habitable: false,
        description: 'Elongated ellipsoid shape due to rapid rotation. Has two moons and a ring system.',
      },
    },
    {
      id: 'sol-hiia',
      name: 'Hi\'iaka',
      type: 'moon',
      parentId: 'sol-haumea',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 13, index: 1 },
      coordinateString: '0:0:0:13:1',
      properties: {
        mass: 1.79e19,
        radius: 160,
        orbitalPeriod: 49.12,
        distanceFromParent: 0.0496,
        surfaceGravity: 0.046,
        meanTemperature: 32,
        atmosphere: [],
        composition: ['Water Ice'],
        habitable: false,
        description: 'Outer and larger moon of Haumea. Nearly pure water ice surface.',
      },
    },
    {
      id: 'sol-namaka',
      name: 'Namaka',
      type: 'moon',
      parentId: 'sol-haumea',
      coordinates: { galaxy: 0, sector: 0, system: 0, orbit: 13, index: 2 },
      coordinateString: '0:0:0:13:2',
      properties: {
        mass: 1.79e18,
        radius: 85,
        orbitalPeriod: 18.28,
        distanceFromParent: 0.0253,
        surfaceGravity: 0.016,
        meanTemperature: 32,
        atmosphere: [],
        composition: ['Water Ice'],
        habitable: false,
        description: 'Inner and smaller moon of Haumea. Named after the Hawaiian sea goddess.',
      },
    },
  ],
};

export const NEARBY_GALAXIES: Galaxy[] = [
  {
    id: 'milky-way',
    name: 'Milky Way',
    type: 'spiral',
    size: 'large',
    starCount: 200000000000,
    diameter: 105700,
    coordinates: { x: 0, y: 0, z: 0 },
  },
  {
    id: 'andromeda',
    name: 'Andromeda (M31)',
    type: 'spiral',
    size: 'giant',
    starCount: 1000000000000,
    diameter: 220000,
    coordinates: { x: 2537000, y: 0, z: 0 },
  },
  {
    id: 'triangulum',
    name: 'Triangulum (M33)',
    type: 'spiral',
    size: 'medium',
    starCount: 40000000000,
    diameter: 60000,
    coordinates: { x: 2730000, y: 200000, z: 0 },
  },
  {
    id: 'lmc',
    name: 'Large Magellanic Cloud',
    type: 'irregular',
    size: 'dwarf',
    starCount: 30000000000,
    diameter: 14000,
    coordinates: { x: 160000, y: -80000, z: 0 },
  },
  {
    id: 'smc',
    name: 'Small Magellanic Cloud',
    type: 'irregular',
    size: 'dwarf',
    starCount: 7000000000,
    diameter: 7000,
    coordinates: { x: 200000, y: -100000, z: 0 },
  },
  {
    id: 'sagittarius-dwarf',
    name: 'Sagittarius Dwarf',
    type: 'elliptical',
    size: 'dwarf',
    starCount: 400000000,
    diameter: 10000,
    coordinates: { x: 70000, y: 0, z: -50000 },
  },
  {
    id: 'ursa-minor-dwarf',
    name: 'Ursa Minor Dwarf',
    type: 'elliptical',
    size: 'dwarf',
    starCount: 10000000,
    diameter: 1000,
    coordinates: { x: 200000, y: 150000, z: 0 },
  },
  {
    id: 'sculptor-dwarf',
    name: 'Sculptor Dwarf',
    type: 'elliptical',
    size: 'dwarf',
    starCount: 100000000,
    diameter: 1000,
    coordinates: { x: 290000, y: -200000, z: 0 },
  },
];

export function getSolSystemPlanets(): CelestialBody[] {
  return SOL_SYSTEM.bodies.filter(b => b.type === 'planet');
}

export function getSolSystemMoons(): CelestialBody[] {
  return SOL_SYSTEM.bodies.filter(b => b.type === 'moon');
}

export function getSolSystemDwarfPlanets(): CelestialBody[] {
  return SOL_SYSTEM.bodies.filter(b => b.type === 'dwarf_planet');
}

export function getCelestialBodyById(id: string): CelestialBody | undefined {
  return SOL_SYSTEM.bodies.find(b => b.id === id);
}

export function getMoonsOfPlanet(planetId: string): CelestialBody[] {
  return SOL_SYSTEM.bodies.filter(b => b.parentId === planetId && b.type === 'moon');
}

export function getBodyByCoordinates(coordString: string): CelestialBody | undefined {
  return SOL_SYSTEM.bodies.find(b => b.coordinateString === coordString);
}
