/**
 * Star Systems Catalog - Complete stellar systems data
 * Contains detailed data for 10+ solar systems with planets, moons, and interstellar objects
 * @tag #starsystems #universe #celestial #planets #moons
 */

import type { StarSystem, Galaxy, CelestialBody, CelestialCoordinates } from './solSystemData';

// ============================================================================
// COORDINATE HELPERS
// ============================================================================

function makeCoords(galaxy: number, sector: number, system: number, orbit: number = 0, index: number = 0): CelestialCoordinates {
  return { galaxy, sector, system, orbit, index };
}

function coordStr(coords: CelestialCoordinates): string {
  return `${coords.galaxy}:${coords.sector}:${coords.system}:${coords.orbit}:${coords.index}`;
}

// ============================================================================
// ===== SYSTEM 1: ALPHA CENTAURI SYSTEM =====
// ============================================================================

export const ALPHA_CENTAURI_SYSTEM: StarSystem = {
  id: 'alpha-centauri',
  name: 'Alpha Centauri System',
  coordinates: makeCoords(1, 102, 9),
  coordinateString: '1:102:9:0:0',
  starType: 'G2V + K1V (Binary)',
  bodies: [
    {
      id: 'ac-alpha-a',
      name: 'Alpha Centauri A',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 102, 9, 0, 0),
      coordinateString: '1:102:9:0:0',
      properties: {
        mass: 2.188e30,
        radius: 854000,
        rotationPeriod: 22,
        surfaceGravity: 274,
        meanTemperature: 5790,
        composition: ['Hydrogen (72%)', 'Helium (26%)', 'Oxygen', 'Carbon', 'Iron'],
        description: 'G2V yellow dwarf, very similar to Sol. Primary star of the Alpha Centauri system.',
      },
    },
    {
      id: 'ac-alpha-b',
      name: 'Alpha Centauri B',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 102, 9, 0, 1),
      coordinateString: '1:102:9:0:1',
      properties: {
        mass: 1.516e30,
        radius: 600000,
        rotationPeriod: 41,
        surfaceGravity: 274,
        meanTemperature: 5260,
        composition: ['Hydrogen (73%)', 'Helium (25%)', 'Oxygen', 'Carbon'],
        description: 'K1V orange dwarf companion to Alpha Centauri A. Slightly cooler and smaller than Sol.',
      },
    },
    {
      id: 'ac-proxima',
      name: 'Proxima Centauri',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 102, 9, 0, 2),
      coordinateString: '1:102:9:0:2',
      properties: {
        mass: 2.428e29,
        radius: 100000,
        rotationPeriod: 82,
        surfaceGravity: 274,
        meanTemperature: 3042,
        composition: ['Hydrogen (74%)', 'Helium (24%)'],
        description: 'M5.5V red dwarf. Closest star to Sol. Part of the Alpha Centauri trinary system.',
      },
    },
    {
      id: 'ac-proxima-b',
      name: 'Proxima Centauri b',
      type: 'planet',
      parentId: 'ac-proxima',
      coordinates: makeCoords(1, 102, 9, 1, 0),
      coordinateString: '1:102:9:1:0',
      properties: {
        mass: 1.27e25,
        radius: 7140,
        orbitalPeriod: 11.2,
        rotationPeriod: 11.2,
        distanceFromParent: 0.0485,
        surfaceGravity: 16.6,
        meanTemperature: 234,
        atmosphere: ['Nitrogen (78%)', 'Oxygen (21%)', 'Argon (1%)'],
        composition: ['Iron', 'Silicate', 'Water'],
        habitable: true,
        description: 'Earth-mass exoplanet in the habitable zone. Tidal locking likely. Prime colonization target.',
      },
    },
    {
      id: 'ac-proxima-d',
      name: 'Proxima Centauri d',
      type: 'planet',
      parentId: 'ac-proxima',
      coordinates: makeCoords(1, 102, 9, 1, 1),
      coordinateString: '1:102:9:1:1',
      properties: {
        mass: 6.0e24,
        radius: 5000,
        orbitalPeriod: 5.1,
        rotationPeriod: 5.1,
        distanceFromParent: 0.029,
        surfaceGravity: 8.0,
        meanTemperature: 250,
        atmosphere: ['Nitrogen', 'Carbon Dioxide'],
        composition: ['Silicate', 'Iron'],
        habitable: false,
        description: 'Sub-Earth planet. Close orbit around Proxima Centauri. Tidal locked.',
      },
    },
    {
      id: 'ac-1',
      name: 'Centauri Prime',
      type: 'planet',
      parentId: 'ac-alpha-a',
      coordinates: makeCoords(1, 102, 9, 2, 0),
      coordinateString: '1:102:9:2:0',
      properties: {
        mass: 8.97e24,
        radius: 8200,
        orbitalPeriod: 287,
        rotationPeriod: 1.2,
        distanceFromParent: 0.98,
        surfaceGravity: 10.2,
        meanTemperature: 295,
        atmosphere: ['Nitrogen (76%)', 'Oxygen (22%)', 'Argon (1%)', 'Carbon Dioxide (0.04%)'],
        composition: ['Iron', 'Silicate', 'Water', 'Organic Materials'],
        habitable: true,
        description: 'Earth-like habitable world orbiting Alpha Centauri A. Abundant oceans and continents.',
      },
    },
    {
      id: 'ac-2',
      name: 'New Eden',
      type: 'planet',
      parentId: 'ac-alpha-a',
      coordinates: makeCoords(1, 102, 9, 2, 1),
      coordinateString: '1:102:9:2:1',
      properties: {
        mass: 6.0e24,
        radius: 6500,
        orbitalPeriod: 450,
        rotationPeriod: 1.5,
        distanceFromParent: 1.42,
        surfaceGravity: 9.5,
        meanTemperature: 260,
        atmosphere: ['Nitrogen (80%)', 'Oxygen (18%)', 'Methane (0.5%)'],
        composition: ['Iron', 'Silicate', 'Water Ice'],
        habitable: true,
        description: 'Cooler habitable world with vast forests and tundra regions. Rich in exotic flora.',
      },
    },
    {
      id: 'ac-3',
      name: 'Burnsgate',
      type: 'planet',
      parentId: 'ac-alpha-a',
      coordinates: makeCoords(1, 102, 9, 2, 2),
      coordinateString: '1:102:9:2:2',
      properties: {
        mass: 3.5e24,
        radius: 3500,
        orbitalPeriod: 150,
        rotationPeriod: 0.8,
        distanceFromParent: 0.4,
        surfaceGravity: 7.2,
        meanTemperature: 850,
        atmosphere: ['Carbon Dioxide (96%)', 'Sulfur Dioxide (3%)'],
        composition: ['Silicate', 'Iron', 'Sulfur'],
        habitable: false,
        description: 'Extreme volcanic world. High surface temperatures from proximity to primary star.',
      },
    },
    {
      id: 'ac-moon-centauri-prime-1',
      name: 'Hope',
      type: 'moon',
      parentId: 'ac-1',
      coordinates: makeCoords(1, 102, 9, 2, 3),
      coordinateString: '1:102:9:2:3',
      properties: {
        mass: 3.5e22,
        radius: 1200,
        orbitalPeriod: 28,
        distanceFromParent: 0.003,
        surfaceGravity: 1.8,
        meanTemperature: 275,
        atmosphere: ['Nitrogen (trace)'],
        composition: ['Silicate', 'Water Ice'],
        habitable: false,
        description: 'Earth-sized moon orbiting Centauri Prime. Thin atmosphere. Potential terraforming target.',
      },
    },
    {
      id: 'ac-moon-centauri-prime-2',
      name: 'Fortitude',
      type: 'moon',
      parentId: 'ac-1',
      coordinates: makeCoords(1, 102, 9, 2, 4),
      coordinateString: '1:102:9:2:4',
      properties: {
        mass: 1.2e22,
        radius: 800,
        orbitalPeriod: 12,
        distanceFromParent: 0.0015,
        surfaceGravity: 1.2,
        meanTemperature: 245,
        atmosphere: [],
        composition: ['Silicate', 'Basalt'],
        habitable: false,
        description: 'Barren rocky moon. Rich in iron and titanium deposits.',
      },
    },
    {
      id: 'ac-belt-1',
      name: 'Centauri Asteroid Belt',
      type: 'asteroid',
      parentId: 'ac-alpha-a',
      coordinates: makeCoords(1, 102, 9, 3, 0),
      coordinateString: '1:102:9:3:0',
      properties: {
        mass: 3.0e20,
        radius: 500,
        orbitalPeriod: 900,
        distanceFromParent: 3.0,
        surfaceGravity: 0.01,
        meanTemperature: 200,
        composition: ['Silicate', 'Metal Ore', 'Ice'],
        habitable: false,
        description: 'Dense asteroid belt between the inner and outer planets. Rich mineral resources.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 2: SIRIUS SYSTEM =====
// ============================================================================

export const SIRIUS_SYSTEM: StarSystem = {
  id: 'sirius',
  name: 'Sirius System',
  coordinates: makeCoords(1, 105, 4),
  coordinateString: '1:105:4:0:0',
  starType: 'A1V + DA (Binary)',
  bodies: [
    {
      id: 'sirius-a',
      name: 'Sirius A',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 105, 4, 0, 0),
      coordinateString: '1:105:4:0:0',
      properties: {
        mass: 3.978e30,
        radius: 1190000,
        rotationPeriod: 16,
        surfaceGravity: 274,
        meanTemperature: 9940,
        composition: ['Hydrogen (71%)', 'Helium (28%)', 'Trace Elements'],
        description: 'A1V white main-sequence star. Brightest star in Earth\'s night sky. 25x more luminous than Sol.',
      },
    },
    {
      id: 'sirius-b',
      name: 'Sirius B',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 105, 4, 0, 1),
      coordinateString: '1:105:4:0:1',
      properties: {
        mass: 1.978e30,
        radius: 5840,
        rotationPeriod: 200,
        surfaceGravity: 10000000,
        meanTemperature: 25200,
        composition: ['Carbon', 'Oxygen', 'Helium'],
        description: 'DA white dwarf. Remnant of a once-massive star. Extremely dense - Earth-sized with solar mass.',
      },
    },
    {
      id: 'sirius-1',
      name: 'Sirius Prime',
      type: 'planet',
      parentId: 'sirius-a',
      coordinates: makeCoords(1, 105, 4, 1, 0),
      coordinateString: '1:105:4:1:0',
      properties: {
        mass: 2.5e25,
        radius: 10500,
        orbitalPeriod: 480,
        rotationPeriod: 0.9,
        distanceFromParent: 1.8,
        surfaceGravity: 14.2,
        meanTemperature: 450,
        atmosphere: ['Nitrogen (65%)', 'Oxygen (20%)', 'Carbon Dioxide (12%)'],
        composition: ['Iron', 'Silicate', 'Heavy Metals'],
        habitable: false,
        description: 'Super-Earth with dense atmosphere. High UV radiation from Sirius A. Dome colonies only.',
      },
    },
    {
      id: 'sirius-2',
      name: 'Sirius Mining Hub',
      type: 'planet',
      parentId: 'sirius-a',
      coordinates: makeCoords(1, 105, 4, 1, 1),
      coordinateString: '1:105:4:1:1',
      properties: {
        mass: 4.0e24,
        radius: 5000,
        orbitalPeriod: 720,
        rotationPeriod: 1.5,
        distanceFromParent: 2.5,
        surfaceGravity: 8.5,
        meanTemperature: 280,
        atmosphere: ['Argon (40%)', 'Carbon Dioxide (35%)', 'Nitrogen (20%)'],
        composition: ['Platinum', 'Iridium', 'Iron', 'Nickel'],
        habitable: false,
        description: 'Mineral-rich planet with heavy metal deposits. Major mining operations. Thin atmosphere.',
      },
    },
    {
      id: 'sirius-3',
      name: 'Sirius Gas Giant',
      type: 'planet',
      parentId: 'sirius-a',
      coordinates: makeCoords(1, 105, 4, 1, 2),
      coordinateString: '1:105:4:1:2',
      properties: {
        mass: 1.2e27,
        radius: 65000,
        orbitalPeriod: 2500,
        rotationPeriod: 0.6,
        distanceFromParent: 5.8,
        surfaceGravity: 22.5,
        meanTemperature: 120,
        atmosphere: ['Hydrogen (85%)', 'Helium (13%)', 'Methane (2%)'],
        composition: ['Hydrogen', 'Helium'],
        rings: true,
        habitable: false,
        description: 'Massive gas giant with a spectacular ring system. Helium-3 rich atmosphere.',
      },
    },
    {
      id: 'sirius-moon-3-1',
      name: 'Helios Station',
      type: 'moon',
      parentId: 'sirius-3',
      coordinates: makeCoords(1, 105, 4, 1, 3),
      coordinateString: '1:105:4:1:3',
      properties: {
        mass: 8.0e21,
        radius: 1500,
        orbitalPeriod: 14,
        distanceFromParent: 0.005,
        surfaceGravity: 1.5,
        meanTemperature: 80,
        atmosphere: ['Methane (trace)'],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Icy moon hosting a major refueling station. Helium-3 extraction facility on surface.',
      },
    },
    {
      id: 'sirius-moon-3-2',
      name: 'Frostbite',
      type: 'moon',
      parentId: 'sirius-3',
      coordinates: makeCoords(1, 105, 4, 1, 4),
      coordinateString: '1:105:4:1:4',
      properties: {
        mass: 3.0e22,
        radius: 2000,
        orbitalPeriod: 32,
        distanceFromParent: 0.009,
        surfaceGravity: 1.8,
        meanTemperature: 60,
        atmosphere: ['Nitrogen (trace)'],
        composition: ['Water Ice', 'Ammonia', 'Rock'],
        habitable: false,
        description: 'Large icy moon with cryovolcanic activity. Subsurface ocean possible.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 3: TRAPPIST-1 SYSTEM =====
// ============================================================================

export const TRAPPIST_SYSTEM: StarSystem = {
  id: 'trappist-1',
  name: 'TRAPPIST-1 System',
  coordinates: makeCoords(1, 150, 35),
  coordinateString: '1:150:35:0:0',
  starType: 'M8V (Ultra-Cool Red Dwarf)',
  bodies: [
    {
      id: 'trappist-star',
      name: 'TRAPPIST-1',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 150, 35, 0, 0),
      coordinateString: '1:150:35:0:0',
      properties: {
        mass: 1.79e29,
        radius: 84000,
        rotationPeriod: 140,
        surfaceGravity: 274,
        meanTemperature: 2550,
        composition: ['Hydrogen (74%)', 'Helium (24%)'],
        description: 'Ultra-cool M8V red dwarf. Very dim but stable. Known for 7 Earth-sized planets.',
      },
    },
    {
      id: 'trappist-b',
      name: 'TRAPPIST-1b',
      type: 'planet',
      parentId: 'trappist-star',
      coordinates: makeCoords(1, 150, 35, 1, 0),
      coordinateString: '1:150:35:1:0',
      properties: {
        mass: 1.02e25,
        radius: 6850,
        orbitalPeriod: 1.5,
        rotationPeriod: 1.5,
        distanceFromParent: 0.011,
        surfaceGravity: 14.5,
        meanTemperature: 400,
        atmosphere: ['Carbon Dioxide (heavy)'],
        composition: ['Silicate', 'Iron'],
        habitable: false,
        description: 'Innermost planet. Tidally locked. Too hot for liquid water on the surface.',
      },
    },
    {
      id: 'trappist-c',
      name: 'TRAPPIST-1c',
      type: 'planet',
      parentId: 'trappist-star',
      coordinates: makeCoords(1, 150, 35, 1, 1),
      coordinateString: '1:150:35:1:1',
      properties: {
        mass: 9.7e24,
        radius: 6700,
        orbitalPeriod: 2.4,
        rotationPeriod: 2.4,
        distanceFromParent: 0.015,
        surfaceGravity: 14.3,
        meanTemperature: 340,
        atmosphere: ['Carbon Dioxide'],
        composition: ['Silicate', 'Iron'],
        habitable: false,
        description: 'Earth-sized. Tidally locked. Dense atmosphere. Too hot for habitation.',
      },
    },
    {
      id: 'trappist-d',
      name: 'TRAPPIST-1d',
      type: 'planet',
      parentId: 'trappist-star',
      coordinates: makeCoords(1, 150, 35, 1, 2),
      coordinateString: '1:150:35:1:2',
      properties: {
        mass: 6.1e24,
        radius: 5800,
        orbitalPeriod: 4.0,
        rotationPeriod: 4.0,
        distanceFromParent: 0.021,
        surfaceGravity: 11.5,
        meanTemperature: 290,
        atmosphere: ['Nitrogen', 'Carbon Dioxide'],
        composition: ['Silicate', 'Iron', 'Water'],
        habitable: true,
        description: 'Inner edge of habitable zone. Possible liquid water. Thin atmosphere.',
      },
    },
    {
      id: 'trappist-e',
      name: 'TRAPPIST-1e',
      type: 'planet',
      parentId: 'trappist-star',
      coordinates: makeCoords(1, 150, 35, 1, 3),
      coordinateString: '1:150:35:1:3',
      properties: {
        mass: 8.2e24,
        radius: 6400,
        orbitalPeriod: 6.1,
        rotationPeriod: 6.1,
        distanceFromParent: 0.029,
        surfaceGravity: 12.6,
        meanTemperature: 275,
        atmosphere: ['Nitrogen (78%)', 'Oxygen (20%)', 'Carbon Dioxide (1%)'],
        composition: ['Iron', 'Silicate', 'Water', 'Organic'],
        habitable: true,
        description: 'BEST HABITABLE CANDIDATE. Earth-like conditions. Oceans likely. Prime colonization world.',
      },
    },
    {
      id: 'trappist-f',
      name: 'TRAPPIST-1f',
      type: 'planet',
      parentId: 'trappist-star',
      coordinates: makeCoords(1, 150, 35, 1, 4),
      coordinateString: '1:150:35:1:4',
      properties: {
        mass: 7.0e24,
        radius: 6200,
        orbitalPeriod: 9.2,
        rotationPeriod: 9.2,
        distanceFromParent: 0.038,
        surfaceGravity: 11.8,
        meanTemperature: 260,
        atmosphere: ['Nitrogen (85%)', 'Carbon Dioxide (12%)'],
        composition: ['Silicate', 'Water Ice', 'Rock'],
        habitable: true,
        description: 'Cooler habitable world. Global ocean with icy continents. Rich in aquatic life.',
      },
    },
    {
      id: 'trappist-g',
      name: 'TRAPPIST-1g',
      type: 'planet',
      parentId: 'trappist-star',
      coordinates: makeCoords(1, 150, 35, 1, 5),
      coordinateString: '1:150:35:1:5',
      properties: {
        mass: 8.5e24,
        radius: 6500,
        orbitalPeriod: 12.4,
        rotationPeriod: 12.4,
        distanceFromParent: 0.047,
        surfaceGravity: 13.0,
        meanTemperature: 255,
        atmosphere: ['Nitrogen', 'Methane'],
        composition: ['Silicate', 'Water Ice', 'Rock'],
        habitable: false,
        description: 'Outer edge of habitable zone. Glacial conditions. Possible subsurface oceans.',
      },
    },
    {
      id: 'trappist-h',
      name: 'TRAPPIST-1h',
      type: 'planet',
      parentId: 'trappist-star',
      coordinates: makeCoords(1, 150, 35, 1, 6),
      coordinateString: '1:150:35:1:6',
      properties: {
        mass: 4.5e24,
        radius: 5200,
        orbitalPeriod: 18.8,
        rotationPeriod: 18.8,
        distanceFromParent: 0.062,
        surfaceGravity: 10.2,
        meanTemperature: 230,
        atmosphere: ['Methane', 'Carbon Dioxide'],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Outermost known planet. Frozen surface with possible subsurface ocean.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 4: PROXIMA / BARNARD'S STAR SYSTEM =====
// ============================================================================

export const BARNARD_SYSTEM: StarSystem = {
  id: 'barnard',
  name: "Barnard's Star System",
  coordinates: makeCoords(1, 120, 18),
  coordinateString: '1:120:18:0:0',
  starType: 'M4V (Red Dwarf)',
  bodies: [
    {
      id: 'barnard-star',
      name: "Barnard's Star",
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 120, 18, 0, 0),
      coordinateString: '1:120:18:0:0',
      properties: {
        mass: 3.08e29,
        radius: 135000,
        rotationPeriod: 130,
        surfaceGravity: 274,
        meanTemperature: 3138,
        composition: ['Hydrogen (73%)', 'Helium (25%)'],
        description: 'M4V red dwarf. Fourth closest star system to Sol. Very old (10+ billion years) and stable.',
      },
    },
    {
      id: 'barnard-b',
      name: "Barnard's Star b",
      type: 'planet',
      parentId: 'barnard-star',
      coordinates: makeCoords(1, 120, 18, 1, 0),
      coordinateString: '1:120:18:1:0',
      properties: {
        mass: 1.03e25,
        radius: 7000,
        orbitalPeriod: 233,
        rotationPeriod: 233,
        distanceFromParent: 0.4,
        surfaceGravity: 12.8,
        meanTemperature: 215,
        atmosphere: ['Nitrogen (80%)', 'Carbon Dioxide (15%)', 'Argon (3%)'],
        composition: ['Silicate', 'Iron', 'Water Ice'],
        habitable: true,
        description: 'Super-Earth in the outer habitable zone. Cold but stable climate. Extensive ice sheets.',
      },
    },
    {
      id: 'barnard-c',
      name: "Barnard's Star c",
      type: 'planet',
      parentId: 'barnard-star',
      coordinates: makeCoords(1, 120, 18, 1, 1),
      coordinateString: '1:120:18:1:1',
      properties: {
        mass: 6.0e24,
        radius: 5500,
        orbitalPeriod: 145,
        rotationPeriod: 145,
        distanceFromParent: 0.27,
        surfaceGravity: 11.0,
        meanTemperature: 250,
        atmosphere: ['Carbon Dioxide (95%)', 'Nitrogen (4%)'],
        composition: ['Silicate', 'Iron'],
        habitable: false,
        description: 'Rocky planet with dense CO2 atmosphere. Runaway greenhouse effect.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 5: VEGA SYSTEM =====
// ============================================================================

export const VEGA_SYSTEM: StarSystem = {
  id: 'vega',
  name: 'Vega System',
  coordinates: makeCoords(1, 150, 21),
  coordinateString: '1:150:21:0:0',
  starType: 'A0V (White Main-Sequence)',
  bodies: [
    {
      id: 'vega-star',
      name: 'Vega',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 150, 21, 0, 0),
      coordinateString: '1:150:21:0:0',
      properties: {
        mass: 4.078e30,
        radius: 1520000,
        rotationPeriod: 12.5,
        surfaceGravity: 274,
        meanTemperature: 9602,
        composition: ['Hydrogen (70%)', 'Helium (28%)', 'Trace Elements'],
        description: 'A0V white main-sequence star. Very bright. Surrounded by a massive debris disk.',
      },
    },
    {
      id: 'vega-1',
      name: 'Vega Prime',
      type: 'planet',
      parentId: 'vega-star',
      coordinates: makeCoords(1, 150, 21, 1, 0),
      coordinateString: '1:150:21:1:0',
      properties: {
        mass: 8.5e24,
        radius: 7500,
        orbitalPeriod: 320,
        rotationPeriod: 1.1,
        distanceFromParent: 2.1,
        surfaceGravity: 11.2,
        meanTemperature: 410,
        atmosphere: ['Nitrogen (60%)', 'Oxygen (25%)', 'Carbon Dioxide (10%)'],
        composition: ['Iron', 'Silicate', 'Heavy Elements'],
        habitable: false,
        description: 'Hot super-Earth. Protected by strong magnetic field. Research colonies studying the star.',
      },
    },
    {
      id: 'vega-2',
      name: 'Vega Station',
      type: 'planet',
      parentId: 'vega-star',
      coordinates: makeCoords(1, 150, 21, 1, 1),
      coordinateString: '1:150:21:1:1',
      properties: {
        mass: 5.0e24,
        radius: 6000,
        orbitalPeriod: 540,
        rotationPeriod: 1.8,
        distanceFromParent: 3.5,
        surfaceGravity: 9.8,
        meanTemperature: 290,
        atmosphere: ['Nitrogen (75%)', 'Oxygen (20%)', 'Argon (3%)'],
        composition: ['Silicate', 'Iron', 'Water'],
        habitable: true,
        description: 'Temperate world with carbon cycle similar to Earth. Extensive cave systems.',
      },
    },
    {
      id: 'vega-belt',
      name: 'Vega Debris Disk',
      type: 'asteroid',
      parentId: 'vega-star',
      coordinates: makeCoords(1, 150, 21, 2, 0),
      coordinateString: '1:150:21:2:0',
      properties: {
        mass: 1.0e22,
        radius: 200,
        orbitalPeriod: 2000,
        distanceFromParent: 80,
        surfaceGravity: 0.001,
        meanTemperature: 50,
        composition: ['Dust', 'Ice', 'Rock', 'Organic Compounds'],
        habitable: false,
        description: 'Massive debris disk similar to early Solar System. Active planet formation zone.',
      },
    },
    {
      id: 'vega-moon-2-1',
      name: 'Reflection',
      type: 'moon',
      parentId: 'vega-2',
      coordinates: makeCoords(1, 150, 21, 1, 2),
      coordinateString: '1:150:21:1:2',
      properties: {
        mass: 2.0e22,
        radius: 1000,
        orbitalPeriod: 18,
        distanceFromParent: 0.0025,
        surfaceGravity: 1.3,
        meanTemperature: 260,
        atmosphere: ['Argon (trace)'],
        composition: ['Silicate', 'Ice'],
        habitable: false,
        description: 'Recreational moon. Bright surface reflects Vega\'s brilliant light. Tourist destination.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 6: POLARIS SYSTEM =====
// ============================================================================

export const POLARIS_SYSTEM: StarSystem = {
  id: 'polaris',
  name: 'Polaris System',
  coordinates: makeCoords(1, 200, 1),
  coordinateString: '1:200:1:0:0',
  starType: 'F7Ib (Yellow Supergiant) + Binary Companions',
  bodies: [
    {
      id: 'polaris-a',
      name: 'Polaris Aa',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 200, 1, 0, 0),
      coordinateString: '1:200:1:0:0',
      properties: {
        mass: 1.26e31,
        radius: 37000000,
        rotationPeriod: 119,
        surfaceGravity: 274,
        meanTemperature: 6015,
        composition: ['Hydrogen (68%)', 'Helium (30%)', 'Carbon', 'Nitrogen'],
        description: 'F7Ib yellow supergiant. The North Star. Cepheid variable used for navigation across the galaxy.',
      },
    },
    {
      id: 'polaris-ab',
      name: 'Polaris Ab',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 200, 1, 0, 1),
      coordinateString: '1:200:1:0:1',
      properties: {
        mass: 3.0e30,
        radius: 600000,
        rotationPeriod: 50,
        surfaceGravity: 274,
        meanTemperature: 6000,
        composition: ['Hydrogen', 'Helium'],
        description: 'F6V main-sequence companion to Polaris Aa. Binocular visible companion.',
      },
    },
    {
      id: 'polaris-1',
      name: 'Navigator',
      type: 'planet',
      parentId: 'polaris-a',
      coordinates: makeCoords(1, 200, 1, 1, 0),
      coordinateString: '1:200:1:1:0',
      properties: {
        mass: 3.0e26,
        radius: 35000,
        orbitalPeriod: 1800,
        rotationPeriod: 0.5,
        distanceFromParent: 7.2,
        surfaceGravity: 25.0,
        meanTemperature: 180,
        atmosphere: ['Hydrogen (80%)', 'Helium (18%)', 'Methane (2%)'],
        composition: ['Hydrogen', 'Helium'],
        rings: true,
        habitable: false,
        description: 'Massive gas giant. Bright rings visible from Polaris\'s light. Important navigation waypoint.',
      },
    },
    {
      id: 'polaris-moon-1-1',
      name: 'Lodestar',
      type: 'moon',
      parentId: 'polaris-1',
      coordinates: makeCoords(1, 200, 1, 1, 1),
      coordinateString: '1:200:1:1:1',
      properties: {
        mass: 5.0e22,
        radius: 2500,
        orbitalPeriod: 20,
        distanceFromParent: 0.008,
        surfaceGravity: 2.0,
        meanTemperature: 100,
        atmosphere: ['Methane', 'Ethane'],
        composition: ['Water Ice', 'Rock', 'Organic Compounds'],
        habitable: false,
        description: 'Major navigational hub. Houses the Polaris Stellar Observatory and Navigation Academy.',
      },
    },
    {
      id: 'polaris-2',
      name: 'Waypoint',
      type: 'planet',
      parentId: 'polaris-a',
      coordinates: makeCoords(1, 200, 1, 1, 2),
      coordinateString: '1:200:1:1:2',
      properties: {
        mass: 2.0e24,
        radius: 4000,
        orbitalPeriod: 900,
        rotationPeriod: 2.5,
        distanceFromParent: 3.8,
        surfaceGravity: 7.5,
        meanTemperature: 250,
        atmosphere: ['Nitrogen (82%)', 'Carbon Dioxide (15%)'],
        composition: ['Silicate', 'Iron'],
        habitable: false,
        description: 'Cold rocky world. Research outpost studying Cepheid variable star behavior.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 7: EPSILON ERIDANI SYSTEM =====
// ============================================================================

export const EPSILON_ERIDANI_SYSTEM: StarSystem = {
  id: 'epsilon-eridani',
  name: 'Epsilon Eridani System',
  coordinates: makeCoords(1, 120, 7),
  coordinateString: '1:120:7:0:0',
  starType: 'K2V (Orange Dwarf)',
  bodies: [
    {
      id: 'ee-star',
      name: 'Epsilon Eridani',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 120, 7, 0, 0),
      coordinateString: '1:120:7:0:0',
      properties: {
        mass: 1.56e30,
        radius: 705000,
        rotationPeriod: 11.2,
        surfaceGravity: 274,
        meanTemperature: 5084,
        composition: ['Hydrogen (73%)', 'Helium (25%)', 'Trace Elements'],
        description: 'K2V orange dwarf. Younger than Sol (500M years). Has an extensive debris disk.',
      },
    },
    {
      id: 'ee-b',
      name: 'Epsilon Eridani b',
      type: 'planet',
      parentId: 'ee-star',
      coordinates: makeCoords(1, 120, 7, 1, 0),
      coordinateString: '1:120:7:1:0',
      properties: {
        mass: 4.8e26,
        radius: 70000,
        orbitalPeriod: 2500,
        rotationPeriod: 0.8,
        distanceFromParent: 3.4,
        surfaceGravity: 20.5,
        meanTemperature: 150,
        atmosphere: ['Hydrogen', 'Helium', 'Ammonia'],
        composition: ['Hydrogen', 'Helium'],
        habitable: false,
        description: 'Jupiter-class gas giant. Outer system planet. Has a massive ring system.',
      },
    },
    {
      id: 'ee-c',
      name: 'Epsilon Eridani c',
      type: 'planet',
      parentId: 'ee-star',
      coordinates: makeCoords(1, 120, 7, 1, 1),
      coordinateString: '1:120:7:1:1',
      properties: {
        mass: 1.2e25,
        radius: 8500,
        orbitalPeriod: 102,
        rotationPeriod: 102,
        distanceFromParent: 0.28,
        surfaceGravity: 14.0,
        meanTemperature: 340,
        atmosphere: ['Carbon Dioxide (95%)', 'Nitrogen (4%)'],
        composition: ['Silicate', 'Iron'],
        habitable: false,
        description: 'Hot super-Earth. Dense atmosphere. Too close to the star for liquid water.',
      },
    },
    {
      id: 'ee-asteroid-belt',
      name: 'Eridani Asteroid Belt',
      type: 'asteroid',
      parentId: 'ee-star',
      coordinates: makeCoords(1, 120, 7, 2, 0),
      coordinateString: '1:120:7:2:0',
      properties: {
        mass: 5.0e21,
        radius: 100,
        orbitalPeriod: 800,
        distanceFromParent: 1.5,
        surfaceGravity: 0.005,
        meanTemperature: 200,
        composition: ['Carbonaceous Chondrite', 'Silicates', 'Metal Ore'],
        habitable: false,
        description: 'Dense asteroid belt between warm zone and outer system. Rich mining region.',
      },
    },
    {
      id: 'ee-d',
      name: 'Eridania',
      type: 'planet',
      parentId: 'ee-star',
      coordinates: makeCoords(1, 120, 7, 1, 2),
      coordinateString: '1:120:7:1:2',
      properties: {
        mass: 7.5e24,
        radius: 6700,
        orbitalPeriod: 187,
        rotationPeriod: 1.5,
        distanceFromParent: 0.48,
        surfaceGravity: 11.5,
        meanTemperature: 280,
        atmosphere: ['Nitrogen (72%)', 'Oxygen (18%)', 'Argon (5%)', 'Carbon Dioxide (3%)'],
        composition: ['Silicate', 'Iron', 'Water', 'Organic'],
        habitable: true,
        description: 'Promising habitable world. Younger biosphere with active geology and carbon cycle.',
      },
    },
    {
      id: 'ee-d-moon',
      name: 'Eridani Haven',
      type: 'moon',
      parentId: 'ee-d',
      coordinates: makeCoords(1, 120, 7, 1, 3),
      coordinateString: '1:120:7:1:3',
      properties: {
        mass: 1.0e22,
        radius: 750,
        orbitalPeriod: 15,
        distanceFromParent: 0.0018,
        surfaceGravity: 0.9,
        meanTemperature: 260,
        atmosphere: ['Nitrogen (trace)'],
        composition: ['Silicate', 'Ice'],
        habitable: false,
        description: 'Small moon with research facility studying the young planetary system.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 8: WOLF 359 SYSTEM =====
// ============================================================================

export const WOLF_359_SYSTEM: StarSystem = {
  id: 'wolf-359',
  name: 'Wolf 359 System',
  coordinates: makeCoords(1, 85, 42),
  coordinateString: '1:85:42:0:0',
  starType: 'M6V (Red Dwarf)',
  bodies: [
    {
      id: 'wolf-star',
      name: 'Wolf 359',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 85, 42, 0, 0),
      coordinateString: '1:85:42:0:0',
      properties: {
        mass: 1.68e29,
        radius: 100000,
        rotationPeriod: 90,
        surfaceGravity: 274,
        meanTemperature: 2800,
        composition: ['Hydrogen (74%)', 'Helium (24%)'],
        description: 'M6V red dwarf. One of the faintest known stars. High flare activity.',
      },
    },
    {
      id: 'wolf-1',
      name: 'Wolf 359b',
      type: 'planet',
      parentId: 'wolf-star',
      coordinates: makeCoords(1, 85, 42, 1, 0),
      coordinateString: '1:85:42:1:0',
      properties: {
        mass: 1.7e25,
        radius: 9500,
        orbitalPeriod: 2.8,
        rotationPeriod: 2.8,
        distanceFromParent: 0.018,
        surfaceGravity: 12.5,
        meanTemperature: 350,
        atmosphere: ['Carbon Dioxide (heavy)'],
        composition: ['Silicate', 'Iron'],
        habitable: false,
        description: 'Hot super-Earth. Tidally locked. Frequent flare events sterilize the surface.',
      },
    },
    {
      id: 'wolf-2',
      name: 'Wolf 359c',
      type: 'planet',
      parentId: 'wolf-star',
      coordinates: makeCoords(1, 85, 42, 1, 1),
      coordinateString: '1:85:42:1:1',
      properties: {
        mass: 5.0e24,
        radius: 5500,
        orbitalPeriod: 5.5,
        rotationPeriod: 5.5,
        distanceFromParent: 0.03,
        surfaceGravity: 11.0,
        meanTemperature: 270,
        atmosphere: ['Nitrogen', 'Carbon Dioxide'],
        composition: ['Silicate', 'Rock'],
        habitable: false,
        description: 'Earth-sized. Faint habitable zone but frequent flares prevent surface life.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 9: LUV / HD 121504 (LUV SYSTEM) =====
// ============================================================================

export const LUV_SYSTEM: StarSystem = {
  id: 'luv',
  name: 'LUV-HD 121504 System',
  coordinates: makeCoords(2, 50, 12),
  coordinateString: '2:50:12:0:0',
  starType: 'G2V (Yellow Dwarf)',
  bodies: [
    {
      id: 'luv-star',
      name: 'LUV Prime',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(2, 50, 12, 0, 0),
      coordinateString: '2:50:12:0:0',
      properties: {
        mass: 2.0e30,
        radius: 700000,
        rotationPeriod: 25,
        surfaceGravity: 274,
        meanTemperature: 5750,
        composition: ['Hydrogen (73%)', 'Helium (25%)', 'Oxygen', 'Carbon'],
        description: 'G2V yellow dwarf nearly identical to Sol. Stable, bright, and life-friendly.',
      },
    },
    {
      id: 'luv-1',
      name: 'LUV-A',
      type: 'planet',
      parentId: 'luv-star',
      coordinates: makeCoords(2, 50, 12, 1, 0),
      coordinateString: '2:50:12:1:0',
      properties: {
        mass: 9.5e24,
        radius: 7800,
        orbitalPeriod: 365,
        rotationPeriod: 1.0,
        distanceFromParent: 1.0,
        surfaceGravity: 10.5,
        meanTemperature: 290,
        atmosphere: ['Nitrogen (77%)', 'Oxygen (21%)', 'Argon (1%)', 'Carbon Dioxide (0.04%)'],
        composition: ['Iron', 'Silicate', 'Water', 'Organic'],
        habitable: true,
        description: 'Perfect Earth analog. Oceans, continents, and a thriving biosphere. Prime colonization world.',
      },
    },
    {
      id: 'luv-2',
      name: 'LUV-B',
      type: 'planet',
      parentId: 'luv-star',
      coordinates: makeCoords(2, 50, 12, 1, 1),
      coordinateString: '2:50:12:1:1',
      properties: {
        mass: 6.0e24,
        radius: 6200,
        orbitalPeriod: 220,
        rotationPeriod: 1.2,
        distanceFromParent: 0.7,
        surfaceGravity: 10.0,
        meanTemperature: 320,
        atmosphere: ['Nitrogen (70%)', 'Oxygen (15%)', 'Carbon Dioxide (12%)'],
        composition: ['Silicate', 'Iron', 'Water'],
        habitable: true,
        description: 'Warm terrestrial world. Higher CO2 levels support dense vegetation. Rich jungle biomes.',
      },
    },
    {
      id: 'luv-moon-2-1',
      name: 'LUV-B Moon',
      type: 'moon',
      parentId: 'luv-2',
      coordinates: makeCoords(2, 50, 12, 1, 2),
      coordinateString: '2:50:12:1:2',
      properties: {
        mass: 3.0e22,
        radius: 1100,
        orbitalPeriod: 22,
        distanceFromParent: 0.003,
        surfaceGravity: 1.6,
        meanTemperature: 300,
        atmosphere: ['Nitrogen (trace)', 'Oxygen (trace)'],
        composition: ['Silicate', 'Ice'],
        habitable: false,
        description: 'Earth-sized moon with thin atmosphere. Possible microbial life in subsurface caves.',
      },
    },
    {
      id: 'luv-3',
      name: 'LUV-C',
      type: 'planet',
      parentId: 'luv-star',
      coordinates: makeCoords(2, 50, 12, 1, 3),
      coordinateString: '2:50:12:1:3',
      properties: {
        mass: 5.0e26,
        radius: 60000,
        orbitalPeriod: 2200,
        rotationPeriod: 0.5,
        distanceFromParent: 3.0,
        surfaceGravity: 22.0,
        meanTemperature: 120,
        atmosphere: ['Hydrogen (85%)', 'Helium (13%)', 'Methane (2%)'],
        composition: ['Hydrogen', 'Helium', 'Ice'],
        rings: true,
        habitable: false,
        description: 'Gas giant with spectacular ring system. Helium-3 mining operations active.',
      },
    },
    {
      id: 'luv-moon-3-1',
      name: 'Gemini',
      type: 'moon',
      parentId: 'luv-3',
      coordinates: makeCoords(2, 50, 12, 1, 4),
      coordinateString: '2:50:12:1:4',
      properties: {
        mass: 4.0e22,
        radius: 1800,
        orbitalPeriod: 16,
        distanceFromParent: 0.004,
        surfaceGravity: 1.8,
        meanTemperature: 80,
        atmosphere: ['Methane (trace)'],
        composition: ['Water Ice', 'Rock', 'Organic Compounds'],
        habitable: false,
        description: 'Icy moon with subsurface ocean. Alien microbial life detected in water plumes.',
      },
    },
    {
      id: 'luv-moon-3-2',
      name: 'Castor',
      type: 'moon',
      parentId: 'luv-3',
      coordinates: makeCoords(2, 50, 12, 1, 5),
      coordinateString: '2:50:12:1:5',
      properties: {
        mass: 1.0e23,
        radius: 2500,
        orbitalPeriod: 32,
        distanceFromParent: 0.007,
        surfaceGravity: 2.2,
        meanTemperature: 70,
        atmosphere: ['Nitrogen (trace)'],
        composition: ['Water Ice', 'Rock'],
        habitable: false,
        description: 'Large moon with cryovolcanoes. Active ice geysers visible from orbit.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 10: RIGEL SYSTEM (BLUE SUPERGIANT) =====
// ============================================================================

export const RIGEL_SYSTEM: StarSystem = {
  id: 'rigel',
  name: 'Rigel System',
  coordinates: makeCoords(1, 250, 8),
  coordinateString: '1:250:8:0:0',
  starType: 'B8Ia (Blue Supergiant) + Binary',
  bodies: [
    {
      id: 'rigel-a',
      name: 'Rigel A',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 250, 8, 0, 0),
      coordinateString: '1:250:8:0:0',
      properties: {
        mass: 3.6e31,
        radius: 58000000,
        rotationPeriod: 90,
        surfaceGravity: 274,
        meanTemperature: 12100,
        composition: ['Hydrogen (65%)', 'Helium (33%)', 'Carbon', 'Nitrogen', 'Oxygen'],
        description: 'B8Ia blue supergiant. One of the most luminous stars known. 120,000x brighter than Sol.',
      },
    },
    {
      id: 'rigel-b',
      name: 'Rigel B',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 250, 8, 0, 1),
      coordinateString: '1:250:8:0:1',
      properties: {
        mass: 8.0e30,
        radius: 1000000,
        rotationPeriod: 40,
        surfaceGravity: 274,
        meanTemperature: 8000,
        composition: ['Hydrogen', 'Helium'],
        description: 'B9V main-sequence companion. Much smaller but still bright compared to most stars.',
      },
    },
    {
      id: 'rigel-1',
      name: 'Inferno',
      type: 'planet',
      parentId: 'rigel-a',
      coordinates: makeCoords(1, 250, 8, 1, 0),
      coordinateString: '1:250:8:1:0',
      properties: {
        mass: 4.0e26,
        radius: 45000,
        orbitalPeriod: 800,
        rotationPeriod: 0.4,
        distanceFromParent: 12.0,
        surfaceGravity: 22.5,
        meanTemperature: 600,
        atmosphere: ['Hydrogen (90%)', 'Helium (9%)', 'Metals'],
        composition: ['Hydrogen', 'Helium', 'Heavy Elements'],
        habitable: false,
        description: 'Massive gas giant. Atmosphere is being stripped by Rigel\'s intense radiation.',
      },
    },
    {
      id: 'rigel-2',
      name: 'Scorched World',
      type: 'planet',
      parentId: 'rigel-a',
      coordinates: makeCoords(1, 250, 8, 1, 1),
      coordinateString: '1:250:8:1:1',
      properties: {
        mass: 2.0e25,
        radius: 12000,
        orbitalPeriod: 420,
        rotationPeriod: 1.5,
        distanceFromParent: 8.5,
        surfaceGravity: 13.5,
        meanTemperature: 850,
        atmosphere: ['Silicate Vapor', 'Metal Vapor'],
        composition: ['Silicate', 'Iron', 'Platinum Group Metals'],
        habitable: false,
        description: 'Super-heated rocky world. Surface molten. Extremely rich in heavy metals.',
      },
    },
    {
      id: 'rigel-belt',
      name: 'Rigel Dust Ring',
      type: 'asteroid',
      parentId: 'rigel-a',
      coordinates: makeCoords(1, 250, 8, 2, 0),
      coordinateString: '1:250:8:2:0',
      properties: {
        mass: 1.0e20,
        radius: 50,
        orbitalPeriod: 5000,
        distanceFromParent: 50,
        surfaceGravity: 0.001,
        meanTemperature: 30,
        composition: ['Dust', 'Ice', 'Rock'],
        habitable: false,
        description: 'Dust ring system illuminated by Rigel\'s brilliant blue-white light.',
      },
    },
  ],
};

// ============================================================================
// ===== SYSTEM 11: TAURI SYSTEM (EXTREME/EXOTIC) =====
// ============================================================================

export const TAURI_SYSTEM: StarSystem = {
  id: 'tauri',
  name: 'Tauri System',
  coordinates: makeCoords(1, 45, 90),
  coordinateString: '1:45:90:0:0',
  starType: 'M2III (Red Giant)',
  bodies: [
    {
      id: 'tauri-star',
      name: 'Tauri Prime',
      type: 'star',
      parentId: null,
      coordinates: makeCoords(1, 45, 90, 0, 0),
      coordinateString: '1:45:90:0:0',
      properties: {
        mass: 5.0e30,
        radius: 35000000,
        rotationPeriod: 200,
        surfaceGravity: 274,
        meanTemperature: 3500,
        composition: ['Hydrogen (70%)', 'Helium (28%)', 'Carbon', 'Oxygen'],
        description: 'M2III red giant. Expanded outer layers. Will eventually form a planetary nebula.',
      },
    },
    {
      id: 'tauri-1',
      name: 'Ember',
      type: 'planet',
      parentId: 'tauri-star',
      coordinates: makeCoords(1, 45, 90, 1, 0),
      coordinateString: '1:45:90:1:0',
      properties: {
        mass: 5.0e24,
        radius: 6000,
        orbitalPeriod: 650,
        rotationPeriod: 2.0,
        distanceFromParent: 2.5,
        surfaceGravity: 10.0,
        meanTemperature: 180,
        atmosphere: ['Nitrogen (45%)', 'Carbon Dioxide (40%)', 'Argon (12%)'],
        composition: ['Silicate', 'Iron'],
        habitable: false,
        description: 'Former habitable world now freezing as the star expanded. Once had oceans.',
      },
    },
    {
      id: 'tauri-2',
      name: 'Cinder',
      type: 'planet',
      parentId: 'tauri-star',
      coordinates: makeCoords(1, 45, 90, 1, 1),
      coordinateString: '1:45:90:1:1',
      properties: {
        mass: 8.0e26,
        radius: 55000,
        orbitalPeriod: 2000,
        rotationPeriod: 0.6,
        distanceFromParent: 5.0,
        surfaceGravity: 24.0,
        meanTemperature: 100,
        atmosphere: ['Hydrogen (80%)', 'Helium (18%)', 'Methane (2%)'],
        composition: ['Hydrogen', 'Helium'],
        habitable: false,
        description: 'Gas giant slowly being consumed by the expanding red giant.',
      },
    },
    {
      id: 'tauri-moon-2-1',
      name: 'Last Hope',
      type: 'moon',
      parentId: 'tauri-2',
      coordinates: makeCoords(1, 45, 90, 1, 2),
      coordinateString: '1:45:90:1:2',
      properties: {
        mass: 1.0e23,
        radius: 2000,
        orbitalPeriod: 25,
        distanceFromParent: 0.006,
        surfaceGravity: 1.5,
        meanTemperature: 200,
        atmosphere: ['Methane', 'Ethane'],
        composition: ['Water Ice', 'Rock', 'Organic Compounds'],
        habitable: false,
        description: 'Research outpost studying stellar death. Ancient alien ruins discovered beneath ice.',
      },
    },
  ],
};

// ============================================================================
// ===== ALL STAR SYSTEMS CATALOG =====
// ============================================================================

export const ALL_STAR_SYSTEMS: StarSystem[] = [
  // Original Sol System is defined in solSystemData.ts
  
  // New systems
  ALPHA_CENTAURI_SYSTEM,
  SIRIUS_SYSTEM,
  TRAPPIST_SYSTEM,
  BARNARD_SYSTEM,
  VEGA_SYSTEM,
  POLARIS_SYSTEM,
  EPSILON_ERIDANI_SYSTEM,
  WOLF_359_SYSTEM,
  LUV_SYSTEM,
  RIGEL_SYSTEM,
  TAURI_SYSTEM,
];

export function getStarSystemById(id: string): StarSystem | undefined {
  return ALL_STAR_SYSTEMS.find(s => s.id === id);
}

export function getStarSystemByCoords(coordStr: string): StarSystem | undefined {
  return ALL_STAR_SYSTEMS.find(s => s.coordinateString === coordStr);
}

export function getStarSystemByName(name: string): StarSystem | undefined {
  return ALL_STAR_SYSTEMS.find(s => s.name.toLowerCase().includes(name.toLowerCase()));
}

export function getBodyInSystem(systemId: string, bodyId: string): CelestialBody | undefined {
  const system = getStarSystemById(systemId);
  if (!system) return undefined;
  return system.bodies.find(b => b.id === bodyId);
}

export function getAllBodies(): CelestialBody[] {
  return ALL_STAR_SYSTEMS.flatMap(s => s.bodies);
}

export function getBodiesByType(type: string): CelestialBody[] {
  return getAllBodies().filter(b => b.type === type);
}

export function getStarSystemsByGalaxy(galaxy: number): StarSystem[] {
  return ALL_STAR_SYSTEMS.filter(s => s.coordinates.galaxy === galaxy);
}

export function getGalaxyStarCount(galaxy: number): number {
  return ALL_STAR_SYSTEMS.filter(s => s.coordinates.galaxy === galaxy).length;
}

export function getTotalHabitablePlanets(): number {
  return getAllBodies().filter(b => b.type === 'planet' && b.properties.habitable).length;
}