// Unit Research Configuration - Research trees for unit types, classes, and classifications
export const UNIT_RESEARCH_CONFIG = {
  // Research categories
  researchCategories: {
    unitTypes: { name: "Unit Types", description: "Unlock new unit types" },
    unitClasses: { name: "Unit Classes", description: "Unlock new unit classes" },
    unitJobs: { name: "Unit Jobs", description: "Unlock new unit jobs and professions" },
    unitTraining: { name: "Unit Training", description: "Improve training effectiveness" },
    unitGenetics: { name: "Unit Genetics", description: "Enhance unit attributes" },
    advancedCombat: { name: "Advanced Combat", description: "Military unit enhancements" },
  },

  // Unit Type Research
  unitTypeResearch: {
    civilianBasics: {
      key: "civilian_basics",
      name: "Civilian Basics",
      category: "unitTypes",
      tier: 1,
      cost: { metal: 1000, crystal: 500, deuterium: 200 },
      time: 3600,
      description: "Unlock basic civilian units (workers, miners)",
      unlocks: ["worker", "miner"],
      prerequisites: [],
    },
    specialistTraining: {
      key: "specialist_training",
      name: "Specialist Training",
      category: "unitTypes",
      tier: 2,
      cost: { metal: 5000, crystal: 3000, deuterium: 1000 },
      time: 7200,
      description: "Unlock specialist units (engineers, scientists)",
      unlocks: ["engineer", "scientist", "medic"],
      prerequisites: ["civilian_basics"],
    },
    militaryRecruit: {
      key: "military_recruit",
      name: "Military Recruitment",
      category: "unitTypes",
      tier: 2,
      cost: { metal: 3000, crystal: 2000, deuterium: 500 },
      time: 5400,
      description: "Unlock military units",
      unlocks: ["soldier", "officer"],
      prerequisites: ["civilian_basics"],
    },
    advancedUnits: {
      key: "advanced_units",
      name: "Advanced Unit Types",
      category: "unitTypes",
      tier: 3,
      cost: { metal: 15000, crystal: 10000, deuterium: 5000 },
      time: 14400,
      description: "Unlock elite and specialized unit variants",
      unlocks: ["elite_soldier", "pilot", "commander"],
      prerequisites: ["military_recruit", "specialist_training"],
    },
  },

  // Unit Class Research
  unitClassResearch: {
    warriorMastery: {
      key: "warrior_mastery",
      name: "Warrior Mastery",
      category: "unitClasses",
      tier: 1,
      cost: { metal: 800, crystal: 400, deuterium: 200 },
      time: 3600,
      description: "Unlock warrior class with +20% physical damage",
      unlocks: ["warrior"],
      prerequisites: [],
      bonuses: { damage: 0.2, armor: 0.15 },
    },
    rangerMarksman: {
      key: "ranger_marksman",
      name: "Ranger Marksman",
      category: "unitClasses",
      tier: 1,
      cost: { metal: 700, crystal: 500, deuterium: 300 },
      time: 3600,
      description: "Unlock ranger class with ranged specialization",
      unlocks: ["ranger"],
      prerequisites: [],
      bonuses: { rangedDamage: 0.2, evasion: 0.15 },
    },
    arcaneStudies: {
      key: "arcane_studies",
      name: "Arcane Studies",
      category: "unitClasses",
      tier: 1,
      cost: { metal: 600, crystal: 1000, deuterium: 500 },
      time: 3600,
      description: "Unlock mage class with spell power",
      unlocks: ["mage"],
      prerequisites: [],
      bonuses: { spellPower: 0.25, manaRegen: 0.2 },
    },
    holyPower: {
      key: "holy_power",
      name: "Holy Power",
      category: "unitClasses",
      tier: 2,
      cost: { metal: 2000, crystal: 2000, deuterium: 1000 },
      time: 7200,
      description: "Unlock paladin class with protection",
      unlocks: ["paladin"],
      prerequisites: ["warrior_mastery", "arcane_studies"],
      bonuses: { armor: 0.2, resistance: 0.15, healing: 1.2 },
    },
    shadowArts: {
      key: "shadow_arts",
      name: "Shadow Arts",
      category: "unitClasses",
      tier: 2,
      cost: { metal: 1500, crystal: 1500, deuterium: 800 },
      time: 7200,
      description: "Unlock rogue class with critical strikes",
      unlocks: ["rogue"],
      prerequisites: ["ranger_marksman"],
      bonuses: { critChance: 0.25, evasion: 0.2, stealth: 1.3 },
    },
  },

  // Unit Job Research
  unitJobResearch: {
    miningTechnique: {
      key: "mining_technique",
      name: "Mining Technique",
      category: "unitJobs",
      tier: 1,
      cost: { metal: 500, crystal: 300, deuterium: 100 },
      time: 1800,
      description: "Improve miner job efficiency by 30%",
      unlocks: ["miner"],
      prerequisites: [],
      bonuses: { mining: 0.3 },
    },
    farmingMastery: {
      key: "farming_mastery",
      name: "Farming Mastery",
      category: "unitJobs",
      tier: 1,
      cost: { metal: 400, crystal: 300, deuterium: 200 },
      time: 1800,
      description: "Improve farmer job efficiency by 40%",
      unlocks: ["farmer"],
      prerequisites: [],
      bonuses: { farming: 0.4 },
    },
    buildingCraft: {
      key: "building_craft",
      name: "Building Craft",
      category: "unitJobs",
      tier: 1,
      cost: { metal: 600, crystal: 400, deuterium: 300 },
      time: 2700,
      description: "Improve builder job efficiency by 35%",
      unlocks: ["builder"],
      prerequisites: [],
      bonuses: { construction: 0.35 },
    },
    engineering: {
      key: "engineering",
      name: "Engineering",
      category: "unitJobs",
      tier: 2,
      cost: { metal: 2000, crystal: 1500, deuterium: 1000 },
      time: 7200,
      description: "Unlock engineer job with advanced tech expertise",
      unlocks: ["engineer"],
      prerequisites: ["building_craft"],
      bonuses: { engineering: 0.4 },
    },
    scientificResearch: {
      key: "scientific_research",
      name: "Scientific Research",
      category: "unitJobs",
      tier: 2,
      cost: { metal: 1500, crystal: 2500, deuterium: 1500 },
      time: 7200,
      description: "Unlock scientist job with research capabilities",
      unlocks: ["scientist"],
      prerequisites: [],
      bonuses: { research: 0.35 },
    },
  },

  // Unit Training Research
  unitTrainingResearch: {
    acceleratedTraining: {
      key: "accelerated_training",
      name: "Accelerated Training",
      category: "unitTraining",
      tier: 1,
      cost: { metal: 1000, crystal: 800, deuterium: 400 },
      time: 3600,
      description: "Reduce training time by 20%",
      trainingMultiplier: 0.8,
      prerequisites: [],
    },
    intensiveConditioning: {
      key: "intensive_conditioning",
      name: "Intensive Conditioning",
      category: "unitTraining",
      tier: 2,
      cost: { metal: 3000, crystal: 2500, deuterium: 1500 },
      time: 7200,
      description: "Reduce training time by 40%, improve stat gains",
      trainingMultiplier: 0.6,
      statGainBonus: 1.25,
      prerequisites: ["accelerated_training"],
    },
    eliteTraining: {
      key: "elite_training",
      name: "Elite Training Program",
      category: "unitTraining",
      tier: 3,
      cost: { metal: 8000, crystal: 6000, deuterium: 4000 },
      time: 14400,
      description: "Reduce training time by 60%, significantly improve stat gains",
      trainingMultiplier: 0.4,
      statGainBonus: 1.5,
      prerequisites: ["intensive_conditioning"],
    },
  },

  // Unit Genetics/Attribute Research
  unitGeneticsResearch: {
    strengthEnhancement: {
      key: "strength_enhancement",
      name: "Strength Enhancement",
      category: "unitGenetics",
      tier: 1,
      cost: { metal: 1200, crystal: 800, deuterium: 500 },
      time: 3600,
      description: "Increase unit strength attribute by 2",
      attributeBonus: { strength: 2 },
      prerequisites: [],
    },
    constitutionBoost: {
      key: "constitution_boost",
      name: "Constitution Boost",
      category: "unitGenetics",
      tier: 1,
      cost: { metal: 1200, crystal: 800, deuterium: 500 },
      time: 3600,
      description: "Increase unit constitution by 2",
      attributeBonus: { constitution: 2 },
      prerequisites: [],
    },
    dexterityTraining: {
      key: "dexterity_training",
      name: "Dexterity Training",
      category: "unitGenetics",
      tier: 1,
      cost: { metal: 1000, crystal: 1200, deuterium: 600 },
      time: 3600,
      description: "Increase unit dexterity by 2",
      attributeBonus: { dexterity: 2 },
      prerequisites: [],
    },
    intellectualAdvancement: {
      key: "intellectual_advancement",
      name: "Intellectual Advancement",
      category: "unitGenetics",
      tier: 1,
      cost: { metal: 800, crystal: 1500, deuterium: 800 },
      time: 3600,
      description: "Increase unit intelligence by 2",
      attributeBonus: { intelligence: 2 },
      prerequisites: [],
    },
    wisdomCultivation: {
      key: "wisdom_cultivation",
      name: "Wisdom Cultivation",
      category: "unitGenetics",
      tier: 1,
      cost: { metal: 900, crystal: 1400, deuterium: 700 },
      time: 3600,
      description: "Increase unit wisdom by 2",
      attributeBonus: { wisdom: 2 },
      prerequisites: [],
    },
    charismaManagement: {
      key: "charisma_management",
      name: "Charisma Management",
      category: "unitGenetics",
      tier: 1,
      cost: { metal: 1000, crystal: 1300, deuterium: 600 },
      time: 3600,
      description: "Increase unit charisma by 2",
      attributeBonus: { charisma: 2 },
      prerequisites: [],
    },
    geneticOptimization: {
      key: "genetic_optimization",
      name: "Genetic Optimization",
      category: "unitGenetics",
      tier: 3,
      cost: { metal: 10000, crystal: 8000, deuterium: 5000 },
      time: 14400,
      description: "Increase all attributes by 3",
      attributeBonus: { strength: 3, constitution: 3, dexterity: 3, intelligence: 3, wisdom: 3, charisma: 3 },
      prerequisites: ["strength_enhancement", "constitution_boost", "dexterity_training", "intellectualAdvancement", "wisdom_cultivation", "charisma_management"],
    },
  },

  // Advanced Combat Research
  advancedCombatResearch: {
    combatTacticsI: {
      key: "combat_tactics_1",
      name: "Combat Tactics I",
      category: "advancedCombat",
      tier: 2,
      cost: { metal: 2000, crystal: 1500, deuterium: 1000 },
      time: 7200,
      description: "Increase soldier damage by 15%",
      damageBonus: 0.15,
      prerequisites: ["military_recruit"],
    },
    advancedCombatTacticsII: {
      key: "combat_tactics_2",
      name: "Combat Tactics II",
      category: "advancedCombat",
      tier: 3,
      cost: { metal: 5000, crystal: 4000, deuterium: 2000 },
      time: 14400,
      description: "Increase soldier damage by 30%, add defensive bonus",
      damageBonus: 0.3,
      armorBonus: 0.2,
      prerequisites: ["combat_tactics_1"],
    },
    formationMastery: {
      key: "formation_mastery",
      name: "Formation Mastery",
      category: "advancedCombat",
      tier: 2,
      cost: { metal: 2500, crystal: 2000, deuterium: 1500 },
      time: 7200,
      description: "Military units gain 25% evasion in formations",
      evasionBonus: 0.25,
      prerequisites: ["military_recruit"],
    },
  },

  // Research progression levels
  researchTiers: {
    1: { name: "Tier 1 - Foundation", minEmpireLevel: 1, pointsRequired: 100 },
    2: { name: "Tier 2 - Advanced", minEmpireLevel: 5, pointsRequired: 500 },
    3: { name: "Tier 3 - Master", minEmpireLevel: 10, pointsRequired: 2000 },
  },

  // Research point generation
  researchPointGeneration: {
    basePointsPerSecond: 1,
    scientistMultiplier: 2.5, // Scientists generate 2.5x points
    baseMultiplier: 1,
    capMultiplier: 2, // Max 2x from facilities/bonuses
  },
};
