export const ASTRONOMY_IMAGES = {
  milkyWay: {
    main: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/ESO-VLT-Laser-phot-33a-07.jpg/1280px-ESO-VLT-Laser-phot-33a-07.jpg",
    panorama: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/NASA-HS201427a-HubbleUltraDeepField2014-20140603.jpg/1280px-NASA-HS201427a-HubbleUltraDeepField2014-20140603.jpg",
    core: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Galacticcentre.jpg/1280px-Galacticcentre.jpg",
    arms: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Milky_Way_Arms.svg/1280px-Milky_Way_Arms.svg.png",
    edge: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/GalacticCenter_%28disambiguation%29.jpg/1280px-GalacticCenter_%28disambiguation%29.jpg",
  },
  planets: {
    mercury: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mercury_in_true_color.jpg/1024px-Mercury_in_true_color.jpg",
    venus: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Venus_from_Mariner_10.jpg/1024px-Venus_from_Mariner_10.jpg",
    earth: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/The_Blue_Marble_%28remastered%29.jpg/1024px-The_Blue_Marble_%28remastered%29.jpg",
    mars: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Mars_-_August_30_2021_-_Flipped.jpg/1024px-Mars_-_August_30_2021_-_Flipped.jpg",
    jupiter: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Jupiter_and_its_shrunken_Great_Red_Spot.jpg/1024px-Jupiter_and_its_shrunken_Great_Red_Spot.jpg",
    saturn: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Saturn_during_Equinox.jpg/1024px-Saturn_during_Equinox.jpg",
    uranus: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Uranus2.jpg/1024px-Uranus2.jpg",
    neptune: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Neptune_Voyager2_color_calibrated.png/1024px-Neptune_Voyager2_color_calibrated.png",
    pluto: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Pluto_in_True_Color_-_High-Res.jpg/1024px-Pluto_in_True_Color_-_High-Res.jpg",
  },
  moons: {
    luna: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/FullMoon2010.jpg/1024px-FullMoon2010.jpg",
    titan: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Titan_in_true_color.jpg/1024px-Titan_in_true_color.jpg",
    europa: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Europa-moon-with-ocean.jpg/1024px-Europa-moon-with-ocean.jpg",
    ganymede: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Ganymede_gjku02f0710.jpg/1024px-Ganymede_gjku02f0710.jpg",
    enceladus: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Enceladus'%27_icy_geysers_%28PIA19002%29.jpg/1024px-Enceladus'%27_icy_geysers_%28PIA19002%29.jpg",
    triton: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Triton_moon_mosaic_Voyager_2_colorized.png/1024px-Triton_moon_mosaic_Voyager_2_colorized.png",
    callisto: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Callisto_ancient_surface.jpg/1024px-Callisto_ancient_surface.jpg",
    io: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Io_highest_resolution_true_color.jpg/1024px-Io_highest_resolution_true_color.jpg",
    miranda: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Miranda_Voyager_2_color_calibrated.png/1024px-Miranda_Voyager_2_color_calibrated.png",
  },
  stars: {
    sun: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg/1024px-The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg",
    betelgeuse: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Betelgeuse_as_seen_by_ALMA_%28ESO%29.png/1024px-Betelgeuse_as_seen_by_ALMA_%28ESO%29.png",
    sirius: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Sirius_A_and_B_artwork.jpg/1024px-Sirius_A_and_B_artwork.jpg",
  },
  galaxies: {
    andromeda: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Andromeda_Galaxy_%28with_h-alpha%29.jpg/1280px-Andromeda_Galaxy_%28with_h-alpha%29.jpg",
    whirlpool: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Whirlpool_Galaxy_by_Hubble.jpg/1280px-Whirlpool_Galaxy_by_Hubble.jpg",
    sombrero: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Sombrero_Galaxy_5600_FL.jpg/1280px-Sombrero_Galaxy_5600_FL.jpg",
    cartwheel: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Potential_host_of_a_massive_black_hole_in_the_Cartwheel_Galaxy.jpg/1280px-Potential_host_of_a_massive_black_hole_in_the_Cartwheel_Galaxy.jpg",
    antennae: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Antennae_Galaxies_by_Hubble.jpg/1280px-Antennae_Galaxies_by_Hubble.jpg",
    trixie: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/ESO-VLT-Laser-phot-33a-07.jpg/1280px-ESO-VLT-Laser-phot-33a-07.jpg",
  },
  nebulae: {
    crab: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Crab_Nebula.jpg/1024px-Crab_Nebula.jpg",
    orion: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Orion_Nebula_-_Hubble_2006_mosaic_18000.jpg/1280px-Orion_Nebula_-_Hubble_2006_mosaic_18000.jpg",
    eagle: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Eagle_nebula_pillars.jpg/1024px-Eagle_nebula_pillars.jpg",
    horsehead: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Barnard_33.jpg/1024px-Barnard_33.jpg",
    pillars: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Pillars_of_creation_2014_HST_WFC3-UVIS_full-res_denoised.jpg/1024px-Pillars_of_creation_2014_HST_WFC3-UVIS_full-res_denoised.jpg",
    ring: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/NGC_7293_%28aka%29.jpg/1024px-NGC_7293_%28aka%29.jpg",
    helix: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Hubble_snapsmscorlib_Hs-2009-25-e-full.jpg/1024px-Hubble_snapsmscorlib_Hs-2009-25-e-full.jpg",
  },
  deepSpace: {
    hubbleDeepField: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Hubble_ultra_deep_field.jpg/1280px-Hubble_ultra_deep_field.jpg",
    hubbleExtreme: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/NASA-HS201427a-HubbleUltraDeepField2014-20140603.jpg/1280px-NASA-HS201427a-HubbleUltraDeepField2014-20140603.jpg",
    cosmicWeb: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Cosmic_computer_web.jpg/1280px-Cosmic_computer_web.jpg",
  },
};

export const PLANET_IMAGE_MAP: Record<string, string> = {
  "sol-mercury": ASTRONOMY_IMAGES.planets.mercury,
  "sol-venus": ASTRONOMY_IMAGES.planets.venus,
  "sol-earth": ASTRONOMY_IMAGES.planets.earth,
  "sol-mars": ASTRONOMY_IMAGES.planets.mars,
  "sol-jupiter": ASTRONOMY_IMAGES.planets.jupiter,
  "sol-saturn": ASTRONOMY_IMAGES.planets.saturn,
  "sol-uranus": ASTRONOMY_IMAGES.planets.uranus,
  "sol-neptune": ASTRONOMY_IMAGES.planets.neptune,
  "sol-pluto": ASTRONOMY_IMAGES.planets.pluto,
  "sol-sun": ASTRONOMY_IMAGES.stars.sun,
  "sol-luna": ASTRONOMY_IMAGES.moons.luna,
  "sol-titan": ASTRONOMY_IMAGES.moons.titan,
  "sol-europa": ASTRONOMY_IMAGES.moons.europa,
  "sol-ganymede": ASTRONOMY_IMAGES.moons.ganymede,
  "sol-enceladus": ASTRONOMY_IMAGES.moons.enceladus,
  "sol-triton": ASTRONOMY_IMAGES.moons.triton,
  "sol-callisto": ASTRONOMY_IMAGES.moons.callisto,
  "sol-io": ASTRONOMY_IMAGES.moons.io,
  "sol-miranda": ASTRONOMY_IMAGES.moons.miranda,
};

export const GALAXY_TYPE_IMAGES: Record<string, string> = {
  spiral: ASTRONOMY_IMAGES.galaxies.whirlpool,
  elliptical: ASTRONOMY_IMAGES.galaxies.sombrero,
  ring: ASTRONOMY_IMAGES.galaxies.cartwheel,
  irregular: ASTRONOMY_IMAGES.galaxies.antennae,
  interacting: ASTRONOMY_IMAGES.galaxies.antennae,
  lenticular: ASTRONOMY_IMAGES.galaxies.sombrero,
};
