export type OgameCatalogEntryType =
  | "building"
  | "research"
  | "ship"
  | "defense"
  | "moon"
  | "officer";

export interface OgameCatalogCost {
  metal: number;
  crystal: number;
  deuterium: number;
  energy?: number;
  darkMatter?: number;
}

export interface OgameCatalogCategoryDefinition {
  id: string;
  name: string;
  description: string;
  sortOrder: number;
}

export interface OgameCatalogEntryDefinition {
  id: string;
  categoryId: string;
  entryType: OgameCatalogEntryType;
  name: string;
  description: string;
  baseCost: OgameCatalogCost;
  baseTimeSeconds: number;
  growthFactor: number;
  prerequisites: Record<string, number>;
  stats: Record<string, number | string | boolean>;
  isMoonOnly?: boolean;
}

export const OGAME_CATALOG_CATEGORIES: OgameCatalogCategoryDefinition[] = [
  {
    id: "economy",
    name: "Economy Buildings",
    description: "Primary resource and energy production structures.",
    sortOrder: 1,
  },
  {
    id: "infrastructure",
    name: "Infrastructure Buildings",
    description: "Storage, construction, and support facilities.",
    sortOrder: 2,
  },
  {
    id: "research",
    name: "Research",
    description: "Empire-wide technology unlocks and combat bonuses.",
    sortOrder: 3,
  },
  {
    id: "fleet",
    name: "Fleet",
    description: "Ships for transport, combat, scouting, and colonization.",
    sortOrder: 4,
  },
  {
    id: "defense",
    name: "Planetary Defense",
    description: "Stationary defenses and missile systems.",
    sortOrder: 5,
  },
  {
    id: "moon",
    name: "Moon Facilities",
    description: "Moon-only facilities for advanced logistics and intel.",
    sortOrder: 6,
  },
  {
    id: "officers",
    name: "Officers",
    description: "Premium-style empire specialists and temporary boosts.",
    sortOrder: 7,
  },
];

export const OGAME_CATALOG_ENTRIES: OgameCatalogEntryDefinition[] = [
  {
    id: "metalMine",
    categoryId: "economy",
    entryType: "building",
    name: "Metal Mine",
    description: "Produces metal each production cycle.",
    baseCost: { metal: 60, crystal: 15, deuterium: 0 },
    baseTimeSeconds: 30,
    growthFactor: 1.5,
    prerequisites: {},
    stats: { metalPerHourBase: 30, energyConsumptionBase: 10 },
  },
  {
    id: "crystalMine",
    categoryId: "economy",
    entryType: "building",
    name: "Crystal Mine",
    description: "Produces crystal each production cycle.",
    baseCost: { metal: 48, crystal: 24, deuterium: 0 },
    baseTimeSeconds: 30,
    growthFactor: 1.6,
    prerequisites: {},
    stats: { crystalPerHourBase: 20, energyConsumptionBase: 10 },
  },
  {
    id: "deuteriumSynthesizer",
    categoryId: "economy",
    entryType: "building",
    name: "Deuterium Synthesizer",
    description: "Extracts deuterium from atmospheric and ice sources.",
    baseCost: { metal: 225, crystal: 75, deuterium: 0 },
    baseTimeSeconds: 45,
    growthFactor: 1.5,
    prerequisites: {},
    stats: { deuteriumPerHourBase: 10, energyConsumptionBase: 20 },
  },
  {
    id: "solarPlant",
    categoryId: "economy",
    entryType: "building",
    name: "Solar Plant",
    description: "Generates energy for mines and facilities.",
    baseCost: { metal: 75, crystal: 30, deuterium: 0 },
    baseTimeSeconds: 30,
    growthFactor: 1.5,
    prerequisites: {},
    stats: { energyProductionBase: 20 },
  },
  {
    id: "fusionReactor",
    categoryId: "economy",
    entryType: "building",
    name: "Fusion Reactor",
    description: "Converts deuterium into high energy output.",
    baseCost: { metal: 900, crystal: 360, deuterium: 180 },
    baseTimeSeconds: 90,
    growthFactor: 1.8,
    prerequisites: { deuteriumSynthesizer: 5, energyTech: 3 },
    stats: { energyProductionBase: 30, deuteriumConsumptionBase: 10 },
  },
  {
    id: "metalStorage",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Metal Storage",
    description: "Increases max metal capacity.",
    baseCost: { metal: 1000, crystal: 0, deuterium: 0 },
    baseTimeSeconds: 40,
    growthFactor: 2,
    prerequisites: {},
    stats: { storageCapacityBase: 10000, storageResource: "metal" },
  },
  {
    id: "crystalStorage",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Crystal Storage",
    description: "Increases max crystal capacity.",
    baseCost: { metal: 1000, crystal: 500, deuterium: 0 },
    baseTimeSeconds: 40,
    growthFactor: 2,
    prerequisites: {},
    stats: { storageCapacityBase: 10000, storageResource: "crystal" },
  },
  {
    id: "deuteriumTank",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Deuterium Tank",
    description: "Increases max deuterium capacity.",
    baseCost: { metal: 1000, crystal: 1000, deuterium: 0 },
    baseTimeSeconds: 40,
    growthFactor: 2,
    prerequisites: {},
    stats: { storageCapacityBase: 10000, storageResource: "deuterium" },
  },
  {
    id: "roboticsFactory",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Robotics Factory",
    description: "Speeds up all building construction.",
    baseCost: { metal: 400, crystal: 120, deuterium: 200 },
    baseTimeSeconds: 120,
    growthFactor: 2,
    prerequisites: {},
    stats: { buildSpeedBonusPerLevel: 0.1 },
  },
  {
    id: "shipyard",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Shipyard",
    description: "Constructs ships and defensive units.",
    baseCost: { metal: 400, crystal: 200, deuterium: 100 },
    baseTimeSeconds: 120,
    growthFactor: 2,
    prerequisites: { roboticsFactory: 2 },
    stats: { shipBuildSpeedBonusPerLevel: 0.1 },
  },
  {
    id: "researchLab",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Research Lab",
    description: "Required for starting and accelerating research.",
    baseCost: { metal: 200, crystal: 400, deuterium: 200 },
    baseTimeSeconds: 120,
    growthFactor: 2,
    prerequisites: {},
    stats: { researchSpeedBonusPerLevel: 0.05 },
  },
  {
    id: "allianceDepot",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Alliance Depot",
    description: "Extends ally fleet fuel support duration.",
    baseCost: { metal: 20000, crystal: 40000, deuterium: 0 },
    baseTimeSeconds: 360,
    growthFactor: 2,
    prerequisites: { shipyard: 4 },
    stats: { supportDurationBonusPerLevel: 0.1 },
  },
  {
    id: "missileSilo",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Missile Silo",
    description: "Stores anti-ballistic and interplanetary missiles.",
    baseCost: { metal: 20000, crystal: 20000, deuterium: 1000 },
    baseTimeSeconds: 300,
    growthFactor: 2,
    prerequisites: { shipyard: 1 },
    stats: { missileSlotsPerLevel: 10 },
  },
  {
    id: "naniteFactory",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Nanite Factory",
    description: "Massively accelerates construction and production queues.",
    baseCost: { metal: 1000000, crystal: 500000, deuterium: 100000 },
    baseTimeSeconds: 600,
    growthFactor: 2,
    prerequisites: { roboticsFactory: 10, computerTech: 10 },
    stats: { queueSpeedMultiplierPerLevel: 2 },
  },
  {
    id: "terraformer",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Terraformer",
    description: "Adds additional building fields on planets.",
    baseCost: { metal: 0, crystal: 50000, deuterium: 100000, energy: 1000 },
    baseTimeSeconds: 480,
    growthFactor: 2,
    prerequisites: { naniteFactory: 1, energyTech: 12 },
    stats: { extraFieldsPerLevel: 5 },
  },
  {
    id: "spaceDock",
    categoryId: "infrastructure",
    entryType: "building",
    name: "Space Dock",
    description: "Recovers a fraction of destroyed ships after battles.",
    baseCost: { metal: 200, crystal: 0, deuterium: 50 },
    baseTimeSeconds: 180,
    growthFactor: 2,
    prerequisites: { shipyard: 2 },
    stats: { fleetRecoveryPercentPerLevel: 0.1 },
  },

  {
    id: "energyTech",
    categoryId: "research",
    entryType: "research",
    name: "Energy Technology",
    description: "Improves energy production and unlock chains.",
    baseCost: { metal: 0, crystal: 800, deuterium: 400 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 1 },
    stats: { energyProductionBonusPerLevel: 0.05 },
  },
  {
    id: "laserTech",
    categoryId: "research",
    entryType: "research",
    name: "Laser Technology",
    description: "Unlocks laser-based ships and defenses.",
    baseCost: { metal: 200, crystal: 100, deuterium: 0 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 1, energyTech: 2 },
    stats: { unlocks: "laser_defense" },
  },
  {
    id: "ionTech",
    categoryId: "research",
    entryType: "research",
    name: "Ion Technology",
    description: "Unlocks ion cannon and advanced ship systems.",
    baseCost: { metal: 1000, crystal: 300, deuterium: 100 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 4, energyTech: 4, laserTech: 5 },
    stats: { ionDamageBonusPerLevel: 0.05 },
  },
  {
    id: "hyperspaceTech",
    categoryId: "research",
    entryType: "research",
    name: "Hyperspace Technology",
    description: "Foundation for hyperspace-capable units and facilities.",
    baseCost: { metal: 0, crystal: 4000, deuterium: 2000 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 7, energyTech: 5, shieldingTech: 5 },
    stats: { cargoBonusPerLevel: 0.05 },
  },
  {
    id: "plasmaTech",
    categoryId: "research",
    entryType: "research",
    name: "Plasma Technology",
    description: "Boosts mines and unlocks plasma turret class.",
    baseCost: { metal: 2000, crystal: 4000, deuterium: 1000 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 4, energyTech: 8, laserTech: 10, ionTech: 5 },
    stats: { mineProductionBonusPerLevel: 0.01 },
  },
  {
    id: "combustionDrive",
    categoryId: "research",
    entryType: "research",
    name: "Combustion Drive",
    description: "Increases speed for basic ship classes.",
    baseCost: { metal: 400, crystal: 0, deuterium: 600 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 1, energyTech: 1 },
    stats: { speedBonusPerLevel: 0.1 },
  },
  {
    id: "impulseDrive",
    categoryId: "research",
    entryType: "research",
    name: "Impulse Drive",
    description: "Increases speed for medium and special ship classes.",
    baseCost: { metal: 2000, crystal: 4000, deuterium: 600 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 2, energyTech: 1, combustionDrive: 5 },
    stats: { speedBonusPerLevel: 0.2 },
  },
  {
    id: "hyperspaceDrive",
    categoryId: "research",
    entryType: "research",
    name: "Hyperspace Drive",
    description: "Increases speed for heavy and capital ship classes.",
    baseCost: { metal: 10000, crystal: 20000, deuterium: 6000 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 7, hyperspaceTech: 3, impulseDrive: 5 },
    stats: { speedBonusPerLevel: 0.3 },
  },
  {
    id: "espionageTech",
    categoryId: "research",
    entryType: "research",
    name: "Espionage Technology",
    description: "Improves espionage report depth and scan chance.",
    baseCost: { metal: 200, crystal: 1000, deuterium: 200 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 3 },
    stats: { espionagePowerPerLevel: 1 },
  },
  {
    id: "computerTech",
    categoryId: "research",
    entryType: "research",
    name: "Computer Technology",
    description: "Increases number of simultaneously controllable fleets.",
    baseCost: { metal: 0, crystal: 400, deuterium: 600 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 1 },
    stats: { fleetsPerLevel: 1 },
  },
  {
    id: "astrophysics",
    categoryId: "research",
    entryType: "research",
    name: "Astrophysics",
    description: "Unlocks additional colony slots and expedition slots.",
    baseCost: { metal: 4000, crystal: 8000, deuterium: 4000 },
    baseTimeSeconds: 54,
    growthFactor: 1.75,
    prerequisites: { researchLab: 3, espionageTech: 4, impulseDrive: 3 },
    stats: { colonySlotsPerOddLevel: 1, expeditionSlotsPerEvenLevel: 1 },
  },
  {
    id: "intergalacticResearchNetwork",
    categoryId: "research",
    entryType: "research",
    name: "Intergalactic Research Network",
    description: "Links remote labs to speed up major projects.",
    baseCost: { metal: 240000, crystal: 400000, deuterium: 160000 },
    baseTimeSeconds: 600,
    growthFactor: 2,
    prerequisites: { researchLab: 10, computerTech: 8, hyperspaceTech: 8 },
    stats: { linkedLabsPerLevel: 1 },
  },
  {
    id: "gravitonTech",
    categoryId: "research",
    entryType: "research",
    name: "Graviton Technology",
    description: "High-energy breakthrough required for extreme projects.",
    baseCost: { metal: 0, crystal: 0, deuterium: 0, energy: 300000 },
    baseTimeSeconds: 1200,
    growthFactor: 3,
    prerequisites: { researchLab: 12, hyperspaceTech: 12 },
    stats: { unlocks: "deathstar" },
  },
  {
    id: "weaponsTech",
    categoryId: "research",
    entryType: "research",
    name: "Weapons Technology",
    description: "Improves attack for fleet and defenses.",
    baseCost: { metal: 800, crystal: 200, deuterium: 0 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 4 },
    stats: { attackBonusPerLevel: 0.1 },
  },
  {
    id: "shieldingTech",
    categoryId: "research",
    entryType: "research",
    name: "Shielding Technology",
    description: "Improves shield strength for fleet and defenses.",
    baseCost: { metal: 200, crystal: 600, deuterium: 0 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 6, energyTech: 3 },
    stats: { shieldBonusPerLevel: 0.1 },
  },
  {
    id: "armourTech",
    categoryId: "research",
    entryType: "research",
    name: "Armour Technology",
    description: "Improves hull and structural points.",
    baseCost: { metal: 1000, crystal: 0, deuterium: 0 },
    baseTimeSeconds: 54,
    growthFactor: 2,
    prerequisites: { researchLab: 2 },
    stats: { hullBonusPerLevel: 0.1 },
  },

  {
    id: "smallCargo",
    categoryId: "fleet",
    entryType: "ship",
    name: "Small Cargo",
    description: "Early logistics vessel.",
    baseCost: { metal: 2000, crystal: 2000, deuterium: 0 },
    baseTimeSeconds: 60,
    growthFactor: 1,
    prerequisites: { shipyard: 2, combustionDrive: 2 },
    stats: { cargo: 5000, speed: 5000, attack: 5, shield: 10, hull: 400 },
  },
  {
    id: "largeCargo",
    categoryId: "fleet",
    entryType: "ship",
    name: "Large Cargo",
    description: "Bulk transport for large empires.",
    baseCost: { metal: 6000, crystal: 6000, deuterium: 0 },
    baseTimeSeconds: 120,
    growthFactor: 1,
    prerequisites: { shipyard: 4, combustionDrive: 6 },
    stats: { cargo: 25000, speed: 7500, attack: 5, shield: 25, hull: 1200 },
  },
  {
    id: "lightFighter",
    categoryId: "fleet",
    entryType: "ship",
    name: "Light Fighter",
    description: "Fast low-cost combat ship.",
    baseCost: { metal: 3000, crystal: 1000, deuterium: 0 },
    baseTimeSeconds: 60,
    growthFactor: 1,
    prerequisites: { shipyard: 1, combustionDrive: 1 },
    stats: { attack: 50, shield: 10, hull: 400, speed: 12500 },
  },
  {
    id: "heavyFighter",
    categoryId: "fleet",
    entryType: "ship",
    name: "Heavy Fighter",
    description: "Improved fighter with stronger hull and guns.",
    baseCost: { metal: 6000, crystal: 4000, deuterium: 0 },
    baseTimeSeconds: 120,
    growthFactor: 1,
    prerequisites: { shipyard: 3, armourTech: 2, impulseDrive: 2 },
    stats: { attack: 150, shield: 25, hull: 1000, speed: 10000 },
  },
  {
    id: "cruiser",
    categoryId: "fleet",
    entryType: "ship",
    name: "Cruiser",
    description: "Balanced anti-fighter combat cruiser.",
    baseCost: { metal: 20000, crystal: 7000, deuterium: 2000 },
    baseTimeSeconds: 300,
    growthFactor: 1,
    prerequisites: { shipyard: 5, impulseDrive: 4, ionTech: 2 },
    stats: { attack: 400, shield: 50, hull: 2700, speed: 15000 },
  },
  {
    id: "battleship",
    categoryId: "fleet",
    entryType: "ship",
    name: "Battleship",
    description: "Heavy line ship for core fleet combat.",
    baseCost: { metal: 45000, crystal: 15000, deuterium: 0 },
    baseTimeSeconds: 480,
    growthFactor: 1,
    prerequisites: { shipyard: 7, hyperspaceDrive: 4 },
    stats: { attack: 1000, shield: 200, hull: 6000, speed: 10000 },
  },
  {
    id: "battlecruiser",
    categoryId: "fleet",
    entryType: "ship",
    name: "Battlecruiser",
    description: "High-speed anti-capital strike ship.",
    baseCost: { metal: 30000, crystal: 40000, deuterium: 15000 },
    baseTimeSeconds: 500,
    growthFactor: 1,
    prerequisites: { shipyard: 8, hyperspaceDrive: 5, laserTech: 12 },
    stats: { attack: 700, shield: 400, hull: 7000, speed: 15000 },
  },
  {
    id: "bomber",
    categoryId: "fleet",
    entryType: "ship",
    name: "Bomber",
    description: "Specialized siege craft against defenses.",
    baseCost: { metal: 50000, crystal: 25000, deuterium: 15000 },
    baseTimeSeconds: 520,
    growthFactor: 1,
    prerequisites: { shipyard: 8, impulseDrive: 6, plasmaTech: 5 },
    stats: { attack: 1000, shield: 500, hull: 7500, speed: 7000 },
  },
  {
    id: "destroyer",
    categoryId: "fleet",
    entryType: "ship",
    name: "Destroyer",
    description: "Heavy anti-capital warship.",
    baseCost: { metal: 60000, crystal: 50000, deuterium: 15000 },
    baseTimeSeconds: 650,
    growthFactor: 1,
    prerequisites: { shipyard: 9, hyperspaceDrive: 6, hyperspaceTech: 5 },
    stats: { attack: 2000, shield: 500, hull: 11000, speed: 5000 },
  },
  {
    id: "deathstar",
    categoryId: "fleet",
    entryType: "ship",
    name: "Deathstar",
    description: "Extreme super-capital platform.",
    baseCost: { metal: 5000000, crystal: 4000000, deuterium: 1000000 },
    baseTimeSeconds: 7200,
    growthFactor: 1,
    prerequisites: { shipyard: 12, hyperspaceTech: 6, gravitonTech: 1 },
    stats: { attack: 200000, shield: 50000, hull: 9000000, speed: 100 },
  },
  {
    id: "recycler",
    categoryId: "fleet",
    entryType: "ship",
    name: "Recycler",
    description: "Collects debris fields into reusable resources.",
    baseCost: { metal: 10000, crystal: 6000, deuterium: 2000 },
    baseTimeSeconds: 180,
    growthFactor: 1,
    prerequisites: { shipyard: 4, combustionDrive: 6, shieldingTech: 2 },
    stats: { cargo: 20000, speed: 2000, attack: 1, shield: 10, hull: 1600 },
  },
  {
    id: "colonyShip",
    categoryId: "fleet",
    entryType: "ship",
    name: "Colony Ship",
    description: "Creates permanent colonies on planets.",
    baseCost: { metal: 10000, crystal: 20000, deuterium: 10000 },
    baseTimeSeconds: 400,
    growthFactor: 1,
    prerequisites: { shipyard: 4, impulseDrive: 3 },
    stats: { cargo: 7500, speed: 2500, attack: 50, shield: 100, hull: 30000 },
  },
  {
    id: "espionageProbe",
    categoryId: "fleet",
    entryType: "ship",
    name: "Espionage Probe",
    description: "Unarmed probe for intelligence operations.",
    baseCost: { metal: 0, crystal: 1000, deuterium: 0 },
    baseTimeSeconds: 20,
    growthFactor: 1,
    prerequisites: { shipyard: 3, espionageTech: 2 },
    stats: { speed: 100000000, attack: 0, shield: 0, hull: 1000 },
  },
  {
    id: "solarSatellite",
    categoryId: "fleet",
    entryType: "ship",
    name: "Solar Satellite",
    description: "Orbital generator built in shipyard queue.",
    baseCost: { metal: 0, crystal: 2000, deuterium: 500 },
    baseTimeSeconds: 40,
    growthFactor: 1,
    prerequisites: { shipyard: 1 },
    stats: { energyProductionBase: 20 },
  },
  {
    id: "pathfinder",
    categoryId: "fleet",
    entryType: "ship",
    name: "Pathfinder",
    description: "Fast scout and support craft.",
    baseCost: { metal: 8000, crystal: 15000, deuterium: 8000 },
    baseTimeSeconds: 260,
    growthFactor: 1,
    prerequisites: { shipyard: 5, hyperspaceDrive: 2 },
    stats: { cargo: 10000, speed: 12000, attack: 200, shield: 200, hull: 10000 },
  },

  {
    id: "rocketLauncher",
    categoryId: "defense",
    entryType: "defense",
    name: "Rocket Launcher",
    description: "Entry-level anti-fleet launcher.",
    baseCost: { metal: 2000, crystal: 0, deuterium: 0 },
    baseTimeSeconds: 25,
    growthFactor: 1,
    prerequisites: { shipyard: 1 },
    stats: { attack: 80, shield: 20, hull: 200 },
  },
  {
    id: "lightLaser",
    categoryId: "defense",
    entryType: "defense",
    name: "Light Laser",
    description: "Reliable anti-fighter defense turret.",
    baseCost: { metal: 1500, crystal: 500, deuterium: 0 },
    baseTimeSeconds: 30,
    growthFactor: 1,
    prerequisites: { shipyard: 2, laserTech: 3 },
    stats: { attack: 100, shield: 25, hull: 200 },
  },
  {
    id: "heavyLaser",
    categoryId: "defense",
    entryType: "defense",
    name: "Heavy Laser",
    description: "Upgraded laser battery for stronger targets.",
    baseCost: { metal: 6000, crystal: 2000, deuterium: 0 },
    baseTimeSeconds: 45,
    growthFactor: 1,
    prerequisites: { shipyard: 4, laserTech: 6, energyTech: 3 },
    stats: { attack: 250, shield: 100, hull: 800 },
  },
  {
    id: "gaussCannon",
    categoryId: "defense",
    entryType: "defense",
    name: "Gauss Cannon",
    description: "High-impact magnetic cannon.",
    baseCost: { metal: 20000, crystal: 15000, deuterium: 2000 },
    baseTimeSeconds: 80,
    growthFactor: 1,
    prerequisites: { shipyard: 6, weaponsTech: 3, shieldingTech: 1 },
    stats: { attack: 1100, shield: 200, hull: 3500 },
  },
  {
    id: "ionCannon",
    categoryId: "defense",
    entryType: "defense",
    name: "Ion Cannon",
    description: "High-shield defensive battery.",
    baseCost: { metal: 2000, crystal: 6000, deuterium: 0 },
    baseTimeSeconds: 45,
    growthFactor: 1,
    prerequisites: { shipyard: 4, ionTech: 4 },
    stats: { attack: 150, shield: 500, hull: 800 },
  },
  {
    id: "plasmaTurret",
    categoryId: "defense",
    entryType: "defense",
    name: "Plasma Turret",
    description: "Heavy endgame anti-capital defense.",
    baseCost: { metal: 50000, crystal: 50000, deuterium: 30000 },
    baseTimeSeconds: 120,
    growthFactor: 1,
    prerequisites: { shipyard: 8, plasmaTech: 7 },
    stats: { attack: 3000, shield: 300, hull: 10000 },
  },
  {
    id: "smallShieldDome",
    categoryId: "defense",
    entryType: "defense",
    name: "Small Shield Dome",
    description: "Planetary shield bubble against small attacks.",
    baseCost: { metal: 10000, crystal: 10000, deuterium: 0 },
    baseTimeSeconds: 300,
    growthFactor: 1,
    prerequisites: { shipyard: 1, shieldingTech: 2 },
    stats: { shieldPoints: 2000, limitPerPlanet: 1 },
  },
  {
    id: "largeShieldDome",
    categoryId: "defense",
    entryType: "defense",
    name: "Large Shield Dome",
    description: "Advanced planetary shield bubble.",
    baseCost: { metal: 50000, crystal: 50000, deuterium: 0 },
    baseTimeSeconds: 600,
    growthFactor: 1,
    prerequisites: { shipyard: 6, shieldingTech: 6 },
    stats: { shieldPoints: 10000, limitPerPlanet: 1 },
  },
  {
    id: "antiBallisticMissile",
    categoryId: "defense",
    entryType: "defense",
    name: "Anti-Ballistic Missile",
    description: "Intercepts incoming interplanetary missiles.",
    baseCost: { metal: 8000, crystal: 0, deuterium: 2000 },
    baseTimeSeconds: 45,
    growthFactor: 1,
    prerequisites: { missileSilo: 2 },
    stats: { interceptionValue: 1 },
  },
  {
    id: "interplanetaryMissile",
    categoryId: "defense",
    entryType: "defense",
    name: "Interplanetary Missile",
    description: "Long-range missile for targeted strikes.",
    baseCost: { metal: 12500, crystal: 2500, deuterium: 10000 },
    baseTimeSeconds: 90,
    growthFactor: 1,
    prerequisites: { missileSilo: 4, impulseDrive: 1 },
    stats: { strikeDamage: 12000 },
  },

  {
    id: "lunarBase",
    categoryId: "moon",
    entryType: "moon",
    name: "Lunar Base",
    description: "Creates available fields on a moon.",
    baseCost: { metal: 20000, crystal: 40000, deuterium: 20000 },
    baseTimeSeconds: 360,
    growthFactor: 2,
    prerequisites: {},
    stats: { moonFieldsPerLevel: 3 },
    isMoonOnly: true,
  },
  {
    id: "sensorPhalanx",
    categoryId: "moon",
    entryType: "moon",
    name: "Sensor Phalanx",
    description: "Scans systems for fleet movement data.",
    baseCost: { metal: 20000, crystal: 40000, deuterium: 20000 },
    baseTimeSeconds: 400,
    growthFactor: 2,
    prerequisites: { lunarBase: 1 },
    stats: { scanRangePerLevel: 3 },
    isMoonOnly: true,
  },
  {
    id: "jumpGate",
    categoryId: "moon",
    entryType: "moon",
    name: "Jump Gate",
    description: "Transfers fleets instantly between moons.",
    baseCost: { metal: 2000000, crystal: 4000000, deuterium: 2000000 },
    baseTimeSeconds: 1800,
    growthFactor: 1.5,
    prerequisites: { lunarBase: 1, hyperspaceTech: 7 },
    stats: { cooldownMinutes: 60 },
    isMoonOnly: true,
  },
  {
    id: "lunarShipyard",
    categoryId: "moon",
    entryType: "moon",
    name: "Lunar Shipyard",
    description: "Constructs moon defenses and support fleets.",
    baseCost: { metal: 50000, crystal: 100000, deuterium: 50000 },
    baseTimeSeconds: 600,
    growthFactor: 2,
    prerequisites: { lunarBase: 2, shipyard: 5 },
    stats: { moonBuildSpeedBonusPerLevel: 0.1 },
    isMoonOnly: true,
  },

  {
    id: "commanderOfficer",
    categoryId: "officers",
    entryType: "officer",
    name: "Commander",
    description: "Adds queue automation and better fleet visibility.",
    baseCost: { metal: 0, crystal: 0, deuterium: 0, darkMatter: 500 },
    baseTimeSeconds: 0,
    growthFactor: 1,
    prerequisites: {},
    stats: { queueSlotsBonus: 2, active: true },
  },
  {
    id: "admiralOfficer",
    categoryId: "officers",
    entryType: "officer",
    name: "Admiral",
    description: "Increases simultaneous fleets and command efficiency.",
    baseCost: { metal: 0, crystal: 0, deuterium: 0, darkMatter: 500 },
    baseTimeSeconds: 0,
    growthFactor: 1,
    prerequisites: {},
    stats: { fleetSlotsBonus: 2, active: true },
  },
  {
    id: "engineerOfficer",
    categoryId: "officers",
    entryType: "officer",
    name: "Engineer",
    description: "Improves defensive shield and structure durability.",
    baseCost: { metal: 0, crystal: 0, deuterium: 0, darkMatter: 500 },
    baseTimeSeconds: 0,
    growthFactor: 1,
    prerequisites: {},
    stats: { defenseDurabilityBonus: 0.1, active: true },
  },
  {
    id: "geologistOfficer",
    categoryId: "officers",
    entryType: "officer",
    name: "Geologist",
    description: "Boosts mining output across all planets.",
    baseCost: { metal: 0, crystal: 0, deuterium: 0, darkMatter: 500 },
    baseTimeSeconds: 0,
    growthFactor: 1,
    prerequisites: {},
    stats: { mineProductionBonus: 0.1, active: true },
  },
  {
    id: "technocratOfficer",
    categoryId: "officers",
    entryType: "officer",
    name: "Technocrat",
    description: "Improves research and espionage throughput.",
    baseCost: { metal: 0, crystal: 0, deuterium: 0, darkMatter: 500 },
    baseTimeSeconds: 0,
    growthFactor: 1,
    prerequisites: {},
    stats: { researchSpeedBonus: 0.25, espionageBonus: 2, active: true },
  },
];

export const OGAME_CATALOG_ENTRY_MAP: Record<string, OgameCatalogEntryDefinition> =
  Object.fromEntries(OGAME_CATALOG_ENTRIES.map((entry) => [entry.id, entry]));
