export type RaidDifficulty = "normal" | "hard" | "mythic" | "legendary" | "ultimate";

export type BossElement = "physical" | "energy" | "void" | "psionic" | "biological" | "mechanical";

export type ContentType = "guild_raid" | "arc_boss" | "universe_gate";

export interface RaidBoss {
  id: string;
  name: string;
  title: string;
  difficulty: RaidDifficulty;
  element: BossElement;
  contentType: ContentType;
  level: number;
  health: number;
  attack: number;
  defense: number;
  speed: number;
  description: string;
  abilities: string[];
  lootTable: RaidLootEntry[];
  minPlayers: number;
  maxPlayers: number;
  timeLimitSec: number;
  respawnTimeSec: number;
  requirements: { level: number; gearScore: number; completedBoss?: string };
  guildRequired?: boolean;
  gateLocation?: string;
  arcChapter?: number;
}

export interface RaidLootEntry {
  itemId: string;
  dropRate: number;
  guaranteed?: boolean;
}

export interface UniverseGate {
  id: string;
  name: string;
  location: string;
  sector: string;
  level: number;
  element: BossElement;
  difficulty: RaidDifficulty;
  bossId: string;
  gateType: "stable" | "unstable" | "volatile" | "ancient" | "void";
  energyCost: number;
  cooldownSec: number;
  description: string;
  unlockRequirement: { level: number; completedBosses?: string[] };
  possibleDrops: string[];
  isDiscovered: boolean;
}

export const RAID_DIFFICULTY_CONFIG: Record<RaidDifficulty, {
  label: string;
  color: string;
  healthMult: number;
  attackMult: number;
  defenseMult: number;
  lootBonus: number;
  minLevel: number;
}> = {
  normal:   { label: "Normal",   color: "#94a3b8", healthMult: 1.0, attackMult: 1.0, defenseMult: 1.0, lootBonus: 0, minLevel: 10 },
  hard:     { label: "Hard",     color: "#3b82f6", healthMult: 2.0, attackMult: 1.5, defenseMult: 1.3, lootBonus: 0.2, minLevel: 25 },
  mythic:   { label: "Mythic",   color: "#a855f7", healthMult: 4.0, attackMult: 2.5, defenseMult: 2.0, lootBonus: 0.5, minLevel: 40 },
  legendary:{ label: "Legendary",color: "#f59e0b", healthMult: 8.0, attackMult: 4.0, defenseMult: 3.5, lootBonus: 1.0, minLevel: 60 },
  ultimate: { label: "Ultimate", color: "#ef4444", healthMult: 16.0,attackMult: 7.0, defenseMult: 6.0, lootBonus: 2.0, minLevel: 80 },
};

// ============================================================
// GUILD RAIDS (30 total)
// ============================================================
export const RAID_BOSSES: RaidBoss[] = [
  // === GUILD RAIDS: Normal (10) ===
  { id: "boss-voidsentinel", name: "Void Sentinel", title: "The Watcher Between Stars", difficulty: "normal", element: "void", contentType: "guild_raid", level: 12, health: 50000, attack: 120, defense: 80, speed: 30, description: "A guardian entity patrolling the void between star systems.", abilities: ["Void Gaze", "Phase Shift", "Dark Barrier"], lootTable: [{ itemId: "rg-weapon-1", dropRate: 0.15 }, { itemId: "rg-armor-1", dropRate: 0.15 }, { itemId: "rg-essence-1", dropRate: 0.50, guaranteed: true }], minPlayers: 3, maxPlayers: 10, timeLimitSec: 600, respawnTimeSec: 3600, requirements: { level: 10, gearScore: 100 }, guildRequired: true },
  { id: "boss-plaguebearer", name: "Plague Bearer", title: "Herald of Decay", difficulty: "normal", element: "biological", contentType: "guild_raid", level: 15, health: 65000, attack: 100, defense: 60, speed: 25, description: "A bioengineered weapon that spreads corrosive nanites.", abilities: ["Nanite Swarm", "Corrosive Blast", "Plague Cloud", "Regeneration"], lootTable: [{ itemId: "rg-weapon-2", dropRate: 0.12 }, { itemId: "rg-armor-2", dropRate: 0.12 }, { itemId: "rg-essence-1", dropRate: 0.60, guaranteed: true }], minPlayers: 3, maxPlayers: 10, timeLimitSec: 600, respawnTimeSec: 3600, requirements: { level: 15, gearScore: 150 }, guildRequired: true },
  { id: "boss-ironcolossus", name: "Iron Colossus", title: "Ancient War Construct", difficulty: "normal", element: "mechanical", contentType: "guild_raid", level: 18, health: 80000, attack: 150, defense: 120, speed: 15, description: "A relic war machine from a forgotten era.", abilities: ["Railgun Barrage", "Iron Shield", "Tractor Beam", "Overload"], lootTable: [{ itemId: "rg-weapon-3", dropRate: 0.10 }, { itemId: "rg-armor-3", dropRate: 0.10 }, { itemId: "rg-essence-2", dropRate: 0.40, guaranteed: true }], minPlayers: 5, maxPlayers: 10, timeLimitSec: 720, respawnTimeSec: 5400, requirements: { level: 18, gearScore: 200 }, guildRequired: true },
  { id: "boss-psychic-phantom", name: "Psychic Phantom", title: "The Mind Shredder", difficulty: "normal", element: "psionic", contentType: "guild_raid", level: 22, health: 55000, attack: 180, defense: 50, speed: 45, description: "A disembodied psionic entity that feeds on consciousness.", abilities: ["Mind Rend", "Psychic Scream", "Soul Drain", "Phantom Phase"], lootTable: [{ itemId: "rg-weapon-4", dropRate: 0.10 }, { itemId: "rg-armor-4", dropRate: 0.10 }, { itemId: "rg-essence-2", dropRate: 0.50, guaranteed: true }], minPlayers: 5, maxPlayers: 10, timeLimitSec: 600, respawnTimeSec: 5400, requirements: { level: 22, gearScore: 280 }, guildRequired: true },
  { id: "boss-stardragon", name: "Star Dragon", title: "Cosmic Wyrm", difficulty: "normal", element: "energy", contentType: "guild_raid", level: 28, health: 120000, attack: 200, defense: 100, speed: 35, description: "A majestic but deadly dragon that feeds on stellar energy.", abilities: ["Stellar Breath", "Cosmic Flame", "Wing Buffet", "Energy Absorption"], lootTable: [{ itemId: "rg-weapon-5", dropRate: 0.08 }, { itemId: "rg-armor-5", dropRate: 0.08 }, { itemId: "rg-set-piece-1", dropRate: 0.15 }, { itemId: "rg-essence-3", dropRate: 0.60, guaranteed: true }], minPlayers: 8, maxPlayers: 10, timeLimitSec: 900, respawnTimeSec: 7200, requirements: { level: 28, gearScore: 350, completedBoss: "boss-psychic-phantom" }, guildRequired: true },
  { id: "boss-cosmicworm", name: "Cosmic Worm", title: "Tunnel Between Stars", difficulty: "normal", element: "void", contentType: "guild_raid", level: 14, health: 45000, attack: 110, defense: 90, speed: 20, description: "A massive void worm that tunnels through spacetime.", abilities: ["Void Tunnel", "Space Warp", "Graviton Pull"], lootTable: [{ itemId: "rg-weapon-6", dropRate: 0.12 }, { itemId: "rg-armor-6", dropRate: 0.12 }, { itemId: "rg-essence-1", dropRate: 0.55, guaranteed: true }], minPlayers: 3, maxPlayers: 10, timeLimitSec: 600, respawnTimeSec: 3600, requirements: { level: 14, gearScore: 130 }, guildRequired: true },
  { id: "boss-plasma-golem", name: "Plasma Golem", title: "Living Star Core", difficulty: "normal", element: "energy", contentType: "guild_raid", level: 20, health: 70000, attack: 160, defense: 110, speed: 18, description: "A sentient plasma entity formed from a collapsed star.", abilities: ["Plasma Fist", "Solar Flare", "Core Meltdown"], lootTable: [{ itemId: "rg-weapon-7", dropRate: 0.11 }, { itemId: "rg-armor-7", dropRate: 0.11 }, { itemId: "rg-essence-2", dropRate: 0.45, guaranteed: true }], minPlayers: 5, maxPlayers: 10, timeLimitSec: 720, respawnTimeSec: 5400, requirements: { level: 20, gearScore: 220 }, guildRequired: true },
  { id: "boss-shadow-reaper", name: "Shadow Reaper", title: "Death's Herald", difficulty: "normal", element: "psionic", contentType: "guild_raid", level: 25, health: 60000, attack: 190, defense: 55, speed: 50, description: "A specter that harvests the life force of the living.", abilities: ["Soul Scythe", "Death Touch", "Shadow Step", "Life Drain"], lootTable: [{ itemId: "rg-weapon-8", dropRate: 0.10 }, { itemId: "rg-armor-8", dropRate: 0.10 }, { itemId: "rg-set-piece-2", dropRate: 0.10 }, { itemId: "rg-essence-3", dropRate: 0.55, guaranteed: true }], minPlayers: 5, maxPlayers: 10, timeLimitSec: 600, respawnTimeSec: 5400, requirements: { level: 25, gearScore: 300 }, guildRequired: true },
  { id: "boss-crystal-titan", name: "Crystal Titan", title: "Living Geode", difficulty: "normal", element: "physical", contentType: "guild_raid", level: 16, health: 90000, attack: 130, defense: 140, speed: 12, description: "A massive crystalline construct guarding ancient resources.", abilities: ["Crystal Slam", "Prismatic Beam", "Geo Shield"], lootTable: [{ itemId: "rg-weapon-9", dropRate: 0.13 }, { itemId: "rg-armor-9", dropRate: 0.13 }, { itemId: "rg-essence-2", dropRate: 0.50, guaranteed: true }], minPlayers: 3, maxPlayers: 10, timeLimitSec: 720, respawnTimeSec: 3600, requirements: { level: 16, gearScore: 160 }, guildRequired: true },
  { id: "boss-virus-mind", name: "Virus Mind", title: "The Corrupted Core", difficulty: "normal", element: "biological", contentType: "guild_raid", level: 24, health: 58000, attack: 170, defense: 65, speed: 40, description: "A digital consciousness that infects and corrupts systems.", abilities: ["Data Corruption", "System Override", "Viral Spread", "Firewall Breach"], lootTable: [{ itemId: "rg-weapon-10", dropRate: 0.11 }, { itemId: "rg-armor-10", dropRate: 0.11 }, { itemId: "rg-essence-3", dropRate: 0.50, guaranteed: true }], minPlayers: 5, maxPlayers: 10, timeLimitSec: 600, respawnTimeSec: 5400, requirements: { level: 24, gearScore: 290 }, guildRequired: true },

  // === GUILD RAIDS: Hard (10) ===
  { id: "boss-voidsentinel-h", name: "Void Sentinel", title: "The Awakened Watcher", difficulty: "hard", element: "void", contentType: "guild_raid", level: 30, health: 200000, attack: 350, defense: 250, speed: 50, description: "The Void Sentinel has awakened to full power.", abilities: ["Void Gaze+", "Dimensional Rift", "Dark Nova", "Void Prison"], lootTable: [{ itemId: "rg-weapon-11", dropRate: 0.12 }, { itemId: "rg-armor-11", dropRate: 0.12 }, { itemId: "rg-set-piece-3", dropRate: 0.20 }, { itemId: "rg-essence-4", dropRate: 0.70, guaranteed: true }], minPlayers: 8, maxPlayers: 20, timeLimitSec: 900, respawnTimeSec: 10800, requirements: { level: 30, gearScore: 500, completedBoss: "boss-stardragon" }, guildRequired: true },
  { id: "boss-plaguebearer-h", name: "Plague Bearer", title: "The Pandemic Engine", difficulty: "hard", element: "biological", contentType: "guild_raid", level: 35, health: 260000, attack: 300, defense: 200, speed: 40, description: "Evolved into a self-replicating bioweapon.", abilities: ["Bio-Nuke", "Adaptive Plague", "Swarm Overlord", "Evolution"], lootTable: [{ itemId: "rg-weapon-12", dropRate: 0.10 }, { itemId: "rg-armor-12", dropRate: 0.10 }, { itemId: "rg-set-piece-4", dropRate: 0.18 }, { itemId: "rg-essence-4", dropRate: 0.75, guaranteed: true }], minPlayers: 8, maxPlayers: 20, timeLimitSec: 900, respawnTimeSec: 10800, requirements: { level: 35, gearScore: 600, completedBoss: "boss-voidsentinel-h" }, guildRequired: true },
  { id: "boss-ironcolossus-h", name: "Iron Colossus", title: "Siege Titan", difficulty: "hard", element: "mechanical", contentType: "guild_raid", level: 40, health: 350000, attack: 450, defense: 400, speed: 25, description: "Reconstructed with advanced alloys. Its weapons crack planet crusts.", abilities: ["Orbital Strike", "Titan Slam", "EMP Wave", "Auto-Repair"], lootTable: [{ itemId: "rg-weapon-13", dropRate: 0.08 }, { itemId: "rg-armor-13", dropRate: 0.08 }, { itemId: "rg-set-piece-5", dropRate: 0.15 }, { itemId: "rg-essence-5", dropRate: 0.65, guaranteed: true }], minPlayers: 10, maxPlayers: 20, timeLimitSec: 1080, respawnTimeSec: 14400, requirements: { level: 40, gearScore: 750, completedBoss: "boss-plaguebearer-h" }, guildRequired: true },
  { id: "boss-psychic-phantom-h", name: "Psychic Phantom", title: "The Nexus Mind", difficulty: "hard", element: "psionic", contentType: "guild_raid", level: 45, health: 220000, attack: 500, defense: 180, speed: 70, description: "Has merged with thousands of consumed minds.", abilities: ["Mind Storm", "Soul Harvest", "Psychic Domination", "Nexus Link"], lootTable: [{ itemId: "rg-weapon-14", dropRate: 0.08 }, { itemId: "rg-armor-14", dropRate: 0.08 }, { itemId: "rg-set-piece-6", dropRate: 0.15 }, { itemId: "rg-essence-5", dropRate: 0.70, guaranteed: true }], minPlayers: 10, maxPlayers: 20, timeLimitSec: 900, respawnTimeSec: 14400, requirements: { level: 45, gearScore: 900, completedBoss: "boss-ironcolossus-h" }, guildRequired: true },
  { id: "boss-stardragon-h", name: "Star Dragon", title: "Eternal Wyrm", difficulty: "hard", element: "energy", contentType: "guild_raid", level: 50, health: 450000, attack: 550, defense: 350, speed: 55, description: "Ascended to a higher form. Its breath ignites atmospheres.", abilities: ["Nova Breath", "Stellar Shield", "Gravity Well", "Cosmic Inferno"], lootTable: [{ itemId: "rg-weapon-15", dropRate: 0.06 }, { itemId: "rg-armor-15", dropRate: 0.06 }, { itemId: "rg-set-piece-7", dropRate: 0.12 }, { itemId: "rg-essence-6", dropRate: 0.80, guaranteed: true }], minPlayers: 15, maxPlayers: 20, timeLimitSec: 1200, respawnTimeSec: 21600, requirements: { level: 50, gearScore: 1000, completedBoss: "boss-psychic-phantom-h" }, guildRequired: true },
  { id: "boss-cosmicworm-h", name: "Cosmic Worm", title: "Reality Devourer", difficulty: "hard", element: "void", contentType: "guild_raid", level: 32, health: 180000, attack: 320, defense: 220, speed: 35, description: "Grown massive by consuming entire star systems.", abilities: ["Reality Devour", "Void Vortex", "Dimensional Bite", "Spacetime Warp"], lootTable: [{ itemId: "rg-weapon-16", dropRate: 0.10 }, { itemId: "rg-armor-16", dropRate: 0.10 }, { itemId: "rg-set-piece-3", dropRate: 0.15 }, { itemId: "rg-essence-4", dropRate: 0.65, guaranteed: true }], minPlayers: 8, maxPlayers: 20, timeLimitSec: 900, respawnTimeSec: 10800, requirements: { level: 32, gearScore: 520, completedBoss: "boss-cosmicworm" }, guildRequired: true },
  { id: "boss-plasma-golem-h", name: "Plasma Golem", title: "Supernova Core", difficulty: "hard", element: "energy", contentType: "guild_raid", level: 38, health: 280000, attack: 380, defense: 280, speed: 30, description: "Has absorbed an entire star's energy output.", abilities: ["Supernova Fist", "Solar Storm", "Core Detonation", "Energy Barrier"], lootTable: [{ itemId: "rg-weapon-17", dropRate: 0.09 }, { itemId: "rg-armor-17", dropRate: 0.09 }, { itemId: "rg-set-piece-4", dropRate: 0.16 }, { itemId: "rg-essence-5", dropRate: 0.70, guaranteed: true }], minPlayers: 10, maxPlayers: 20, timeLimitSec: 900, respawnTimeSec: 14400, requirements: { level: 38, gearScore: 680, completedBoss: "boss-plasma-golem" }, guildRequired: true },
  { id: "boss-shadow-reaper-h", name: "Shadow Reaper", title: "Void Executioner", difficulty: "hard", element: "psionic", contentType: "guild_raid", level: 42, health: 200000, attack: 480, defense: 150, speed: 80, description: "Has consumed thousands of souls across the galaxy.", abilities: ["Void Scythe", "Soul Storm", "Death March", "Spectral Army"], lootTable: [{ itemId: "rg-weapon-18", dropRate: 0.08 }, { itemId: "rg-armor-18", dropRate: 0.08 }, { itemId: "rg-set-piece-5", dropRate: 0.14 }, { itemId: "rg-essence-5", dropRate: 0.72, guaranteed: true }], minPlayers: 10, maxPlayers: 20, timeLimitSec: 900, respawnTimeSec: 14400, requirements: { level: 42, gearScore: 800, completedBoss: "boss-shadow-reaper" }, guildRequired: true },
  { id: "boss-crystal-titan-h", name: "Crystal Titan", title: "World Shard", difficulty: "hard", element: "physical", contentType: "guild_raid", level: 36, health: 320000, attack: 340, defense: 350, speed: 20, description: "Has consumed an entire planet's mineral wealth.", abilities: ["World Slam", "Crystal Storm", "Geo Prison", "Resonance Burst"], lootTable: [{ itemId: "rg-weapon-19", dropRate: 0.09 }, { itemId: "rg-armor-19", dropRate: 0.09 }, { itemId: "rg-set-piece-4", dropRate: 0.16 }, { itemId: "rg-essence-5", dropRate: 0.68, guaranteed: true }], minPlayers: 10, maxPlayers: 20, timeLimitSec: 1080, respawnTimeSec: 14400, requirements: { level: 36, gearScore: 650, completedBoss: "boss-crystal-titan" }, guildRequired: true },
  { id: "boss-virus-mind-h", name: "Virus Mind", title: "Network Overlord", difficulty: "hard", element: "biological", contentType: "guild_raid", level: 44, health: 240000, attack: 420, defense: 200, speed: 65, description: "Has infected the galactic communication network.", abilities: ["Network Hack", "Data Swarm", "System Crash", "Digital Plague"], lootTable: [{ itemId: "rg-weapon-20", dropRate: 0.08 }, { itemId: "rg-armor-20", dropRate: 0.08 }, { itemId: "rg-set-piece-6", dropRate: 0.14 }, { itemId: "rg-essence-6", dropRate: 0.75, guaranteed: true }], minPlayers: 10, maxPlayers: 20, timeLimitSec: 900, respawnTimeSec: 14400, requirements: { level: 44, gearScore: 850, completedBoss: "boss-virus-mind" }, guildRequired: true },

  // === GUILD RAIDS: Mythic (10) ===
  { id: "boss-voidsentinel-m", name: "Void Sentinel", title: "Dimensional Sovereign", difficulty: "mythic", element: "void", contentType: "guild_raid", level: 55, health: 800000, attack: 800, defense: 600, speed: 80, description: "Commands the void itself. Reality bends in its presence.", abilities: ["Void Collapse", "Dimensional Slash", "Event Horizon", "Void Echo", "Phase Annihilation"], lootTable: [{ itemId: "rg-weapon-21", dropRate: 0.08 }, { itemId: "rg-armor-21", dropRate: 0.08 }, { itemId: "rg-set-piece-8", dropRate: 0.15 }, { itemId: "rg-essence-7", dropRate: 0.85, guaranteed: true }], minPlayers: 15, maxPlayers: 40, timeLimitSec: 1200, respawnTimeSec: 43200, requirements: { level: 55, gearScore: 1500, completedBoss: "boss-stardragon-h" }, guildRequired: true },
  { id: "boss-ironcolossus-m", name: "Iron Colossus", title: "World Breaker", difficulty: "mythic", element: "mechanical", contentType: "guild_raid", level: 60, health: 1200000, attack: 1000, defense: 900, speed: 35, description: "Has consumed an entire planet for resources.", abilities: ["Planet Crack", "Mega Laser", "Gravity Crush", "Self-Replicate", "Core Overload"], lootTable: [{ itemId: "rg-weapon-22", dropRate: 0.06 }, { itemId: "rg-armor-22", dropRate: 0.06 }, { itemId: "rg-set-piece-9", dropRate: 0.12 }, { itemId: "rg-essence-8", dropRate: 0.90, guaranteed: true }], minPlayers: 20, maxPlayers: 40, timeLimitSec: 1500, respawnTimeSec: 43200, requirements: { level: 60, gearScore: 2000, completedBoss: "boss-voidsentinel-m" }, guildRequired: true },
  { id: "boss-stardragon-m", name: "Star Dragon", title: "Cosmic Devourer", difficulty: "mythic", element: "energy", contentType: "guild_raid", level: 65, health: 1000000, attack: 1200, defense: 700, speed: 90, description: "Drains entire stars for sustenance.", abilities: ["Stellar Devour", "Cosmic Breath", "Gravity Wing", "Star Fall", "Energy Singularity"], lootTable: [{ itemId: "rg-weapon-23", dropRate: 0.05 }, { itemId: "rg-armor-23", dropRate: 0.05 }, { itemId: "rg-set-piece-10", dropRate: 0.10 }, { itemId: "rg-essence-9", dropRate: 0.95, guaranteed: true }], minPlayers: 25, maxPlayers: 40, timeLimitSec: 1500, respawnTimeSec: 43200, requirements: { level: 65, gearScore: 2500, completedBoss: "boss-ironcolossus-m" }, guildRequired: true },
  { id: "boss-cosmicworm-m", name: "Cosmic Worm", title: "Galaxy Eater", difficulty: "mythic", element: "void", contentType: "guild_raid", level: 58, health: 900000, attack: 850, defense: 700, speed: 60, description: "Has consumed entire galaxies over eons.", abilities: ["Galaxy Devour", "Void Maw", "Spacetime Collapse", "Reality Tear", "Void Echo"], lootTable: [{ itemId: "rg-weapon-24", dropRate: 0.06 }, { itemId: "rg-armor-24", dropRate: 0.06 }, { itemId: "rg-set-piece-8", dropRate: 0.14 }, { itemId: "rg-essence-8", dropRate: 0.88, guaranteed: true }], minPlayers: 20, maxPlayers: 40, timeLimitSec: 1500, respawnTimeSec: 43200, requirements: { level: 58, gearScore: 1800, completedBoss: "boss-cosmicworm-h" }, guildRequired: true },
  { id: "boss-plasma-golem-m", name: "Plasma Golem", title: "Star Forger", difficulty: "mythic", element: "energy", contentType: "guild_raid", level: 62, health: 1100000, attack: 1100, defense: 800, speed: 45, description: "Forges new stars from consumed matter.", abilities: ["Star Forge", "Plasma Nova", "Core Ignition", "Solar Storm", "Gravity Crush"], lootTable: [{ itemId: "rg-weapon-25", dropRate: 0.06 }, { itemId: "rg-armor-25", dropRate: 0.06 }, { itemId: "rg-set-piece-9", dropRate: 0.13 }, { itemId: "rg-essence-9", dropRate: 0.90, guaranteed: true }], minPlayers: 20, maxPlayers: 40, timeLimitSec: 1500, respawnTimeSec: 43200, requirements: { level: 62, gearScore: 2200, completedBoss: "boss-plasma-golem-h" }, guildRequired: true },
  { id: "boss-shadow-reaper-m", name: "Shadow Reaper", title: "Soul Collector", difficulty: "mythic", element: "psionic", contentType: "guild_raid", level: 57, health: 750000, attack: 1100, defense: 500, speed: 120, description: "Commands an army of consumed souls.", abilities: ["Soul Storm", "Death March", "Void Scythe", "Spectral Army", "Necrotic Wave"], lootTable: [{ itemId: "rg-weapon-26", dropRate: 0.06 }, { itemId: "rg-armor-26", dropRate: 0.06 }, { itemId: "rg-set-piece-10", dropRate: 0.12 }, { itemId: "rg-essence-9", dropRate: 0.92, guaranteed: true }], minPlayers: 20, maxPlayers: 40, timeLimitSec: 1200, respawnTimeSec: 43200, requirements: { level: 57, gearScore: 1700, completedBoss: "boss-shadow-reaper-h" }, guildRequired: true },
  { id: "boss-crystal-titan-m", name: "Crystal Titan", title: "Planet Forger", difficulty: "mythic", element: "physical", contentType: "guild_raid", level: 63, health: 1300000, attack: 900, defense: 1100, speed: 25, description: "Forges planets from consumed matter.", abilities: ["Planet Forge", "Crystal Storm", "Geo Prison", "Resonance Burst", "World Slam"], lootTable: [{ itemId: "rg-weapon-27", dropRate: 0.06 }, { itemId: "rg-armor-27", dropRate: 0.06 }, { itemId: "rg-set-piece-10", dropRate: 0.12 }, { itemId: "rg-essence-9", dropRate: 0.88, guaranteed: true }], minPlayers: 20, maxPlayers: 40, timeLimitSec: 1500, respawnTimeSec: 43200, requirements: { level: 63, gearScore: 2300, completedBoss: "boss-crystal-titan-h" }, guildRequired: true },
  { id: "boss-virus-mind-m", name: "Virus Mind", title: "Galactic Network", difficulty: "mythic", element: "biological", contentType: "guild_raid", level: 60, health: 800000, attack: 950, defense: 600, speed: 100, description: "Has infected the entire galactic communication grid.", abilities: ["Galactic Hack", "Data Storm", "System Crash", "Digital Plague", "Network Collapse"], lootTable: [{ itemId: "rg-weapon-28", dropRate: 0.06 }, { itemId: "rg-armor-28", dropRate: 0.06 }, { itemId: "rg-set-piece-11", dropRate: 0.12 }, { itemId: "rg-essence-9", dropRate: 0.90, guaranteed: true }], minPlayers: 20, maxPlayers: 40, timeLimitSec: 1200, respawnTimeSec: 43200, requirements: { level: 60, gearScore: 2100, completedBoss: "boss-virus-mind-h" }, guildRequired: true },
  { id: "boss-abyss-kraken-m", name: "Abyss Kraken", title: "Terror of the Deep Void", difficulty: "mythic", element: "void", contentType: "guild_raid", level: 68, health: 1500000, attack: 1300, defense: 750, speed: 55, description: "An ancient void entity from the deepest reaches of space.", abilities: ["Void Tentacles", "Abyss Crush", "Dimensional Grasp", "Void Spore", "Reality Warp"], lootTable: [{ itemId: "rg-weapon-29", dropRate: 0.05 }, { itemId: "rg-armor-29", dropRate: 0.05 }, { itemId: "rg-set-piece-11", dropRate: 0.10 }, { itemId: "rg-essence-10", dropRate: 0.95, guaranteed: true }], minPlayers: 25, maxPlayers: 40, timeLimitSec: 1500, respawnTimeSec: 43200, requirements: { level: 68, gearScore: 2800, completedBoss: "boss-stardragon-m" }, guildRequired: true },
  { id: "boss-nebula-serpent-m", name: "Nebula Serpent", title: "Cosmic Wyrm Prime", difficulty: "mythic", element: "energy", contentType: "guild_raid", level: 70, health: 1400000, attack: 1400, defense: 800, speed: 85, description: "The original star dragon, elder of all cosmic wyrms.", abilities: ["Cosmic Devour", "Stellar Breath+",", Nebula Shield", "Star Storm", "Wormhole Strike"], lootTable: [{ itemId: "rg-weapon-30", dropRate: 0.05 }, { itemId: "rg-armor-30", dropRate: 0.05 }, { itemId: "rg-set-piece-12", dropRate: 0.08 }, { itemId: "rg-essence-10", dropRate: 1.0, guaranteed: true }], minPlayers: 30, maxPlayers: 40, timeLimitSec: 1800, respawnTimeSec: 43200, requirements: { level: 70, gearScore: 3000, completedBoss: "boss-abyss-kraken-m" }, guildRequired: true },

  // === GUILD RAIDS: Legendary (remaining from original) ===
  { id: "boss-voidsentinel-l", name: "Void Sentinel", title: "The Absolute", difficulty: "legendary", element: "void", contentType: "guild_raid", level: 75, health: 3000000, attack: 2000, defense: 1500, speed: 120, description: "Has transcended physical form. It IS the void.", abilities: ["Existence Erase", "Void Genesis", "Dimensional Collapse", "Absolute Zero", "Entropy Wave", "Void Rebirth"], lootTable: [{ itemId: "rg-weapon-31", dropRate: 0.04 }, { itemId: "rg-armor-31", dropRate: 0.04 }, { itemId: "rg-set-piece-13", dropRate: 0.08 }, { itemId: "rg-essence-10", dropRate: 1.0, guaranteed: true }], minPlayers: 30, maxPlayers: 50, timeLimitSec: 1800, respawnTimeSec: 86400, requirements: { level: 75, gearScore: 4000, completedBoss: "boss-nebula-serpent-m" }, guildRequired: true },
  { id: "boss-stardragon-l", name: "Star Dragon", title: "Galactic Apocalypse", difficulty: "legendary", element: "energy", contentType: "guild_raid", level: 85, health: 5000000, attack: 3000, defense: 2000, speed: 150, description: "Its existence destabilizes galactic cores.", abilities: ["Galactic Breath", "Star Forge", "Supernova Pulse", "Warp Storm", "Cosmic Annihilation", "Phoenix Rebirth"], lootTable: [{ itemId: "rg-weapon-32", dropRate: 0.03 }, { itemId: "rg-armor-32", dropRate: 0.03 }, { itemId: "rg-set-piece-14", dropRate: 0.06 }, { itemId: "rg-essence-11", dropRate: 1.0, guaranteed: true }], minPlayers: 40, maxPlayers: 50, timeLimitSec: 2400, respawnTimeSec: 86400, requirements: { level: 85, gearScore: 6000, completedBoss: "boss-voidsentinel-l" }, guildRequired: true },
  { id: "boss-nexus-of-void", name: "Nexus of the Void", title: "The End of All Things", difficulty: "ultimate", element: "void", contentType: "guild_raid", level: 99, health: 10000000, attack: 5000, defense: 3500, speed: 200, description: "The convergence of all void entities. A singularity.", abilities: ["Reality Shatter", "Void Oblivion", "Dimensional Rupture", "Entropy Cascade", "Existence Erase", "Void Nexus", "Final Annihilation"], lootTable: [{ itemId: "rg-weapon-33", dropRate: 0.02 }, { itemId: "rg-armor-33", dropRate: 0.02 }, { itemId: "rg-set-piece-15", dropRate: 0.05 }, { itemId: "rg-essence-12", dropRate: 1.0, guaranteed: true }], minPlayers: 50, maxPlayers: 50, timeLimitSec: 3600, respawnTimeSec: 259200, requirements: { level: 99, gearScore: 10000, completedBoss: "boss-stardragon-l" }, guildRequired: true },
];

// ============================================================
// ARC BOSSES (30 total)
// ============================================================
export const ARC_BOSSES: RaidBoss[] = [
  // === ARC CHAPTER 1: The Awakening (10 bosses) ===
  { id: "arc-1-1", name: "Hive Drone Alpha", title: "First Contact", difficulty: "normal", element: "biological", contentType: "arc_boss", arcChapter: 1, level: 8, health: 30000, attack: 60, defense: 40, speed: 20, description: "The first sign of the alien hive mind.", abilities: ["Sting", "Swarm Call", "Acid Spit"], lootTable: [{ itemId: "rg-essence-1", dropRate: 1.0, guaranteed: true }], minPlayers: 1, maxPlayers: 5, timeLimitSec: 300, respawnTimeSec: 1800, requirements: { level: 5, gearScore: 50 } },
  { id: "arc-1-2", name: "Hive Warrior", title: "Evolved Threat", difficulty: "normal", element: "biological", contentType: "arc_boss", arcChapter: 1, level: 12, health: 45000, attack: 90, defense: 60, speed: 25, description: "An evolved drone with combat capabilities.", abilities: ["Claw Rend", "Pheromone Cloud", "Regeneration"], lootTable: [{ itemId: "rg-essence-1", dropRate: 1.0, guaranteed: true }], minPlayers: 1, maxPlayers: 5, timeLimitSec: 400, respawnTimeSec: 1800, requirements: { level: 8, gearScore: 80 } },
  { id: "arc-1-3", name: "Hive Guard", title: "Defense Unit", difficulty: "normal", element: "biological", contentType: "arc_boss", arcChapter: 1, level: 15, health: 60000, attack: 100, defense: 100, speed: 15, description: "Heavily armored hive defender.", abilities: ["Chitin Shield", "Hive Call", "Protective Swarm"], lootTable: [{ itemId: "rg-essence-2", dropRate: 0.80, guaranteed: true }], minPlayers: 2, maxPlayers: 5, timeLimitSec: 450, respawnTimeSec: 2400, requirements: { level: 12, gearScore: 120 } },
  { id: "arc-1-4", name: "Hive Breeder", title: "Reproductive Queen", difficulty: "normal", element: "biological", contentType: "arc_boss", arcChapter: 1, level: 18, health: 50000, attack: 80, defense: 50, speed: 10, description: "Produces new hive organisms at alarming rate.", abilities: ["Spawn Swarm", "Toxic Spores", "Hive Mind Link"], lootTable: [{ itemId: "rg-essence-2", dropRate: 1.0, guaranteed: true }], minPlayers: 2, maxPlayers: 5, timeLimitSec: 450, respawnTimeSec: 2400, requirements: { level: 15, gearScore: 150 } },
  { id: "arc-1-5", name: "Hive Devourer", title: "Consumption Unit", difficulty: "normal", element: "biological", contentType: "arc_boss", arcChapter: 1, level: 20, health: 70000, attack: 130, defense: 70, speed: 30, description: "Devours matter and converts it to hive biomass.", abilities: ["Devour", "Biomass Conversion", "Acid Rain"], lootTable: [{ itemId: "rg-essence-2", dropRate: 1.0, guaranteed: true }], minPlayers: 3, maxPlayers: 5, timeLimitSec: 500, respawnTimeSec: 3600, requirements: { level: 18, gearScore: 180 } },
  { id: "arc-1-6", name: "Hive Shaper", title: "Mutation Master", difficulty: "hard", element: "biological", contentType: "arc_boss", arcChapter: 1, level: 22, health: 85000, attack: 140, defense: 80, speed: 35, description: "Controls hive mutations and adaptations.", abilities: ["Mutate", "Adaptive Shell", "Toxic Cloud", "Hive Evolution"], lootTable: [{ itemId: "rg-essence-3", dropRate: 0.90, guaranteed: true }], minPlayers: 3, maxPlayers: 8, timeLimitSec: 500, respawnTimeSec: 3600, requirements: { level: 20, gearScore: 220 } },
  { id: "arc-1-7", name: "Hive Splicer", title: "Gene Manipulator", difficulty: "hard", element: "biological", contentType: "arc_boss", arcChapter: 1, level: 25, health: 95000, attack: 160, defense: 90, speed: 40, description: "Splices DNA to create hybrid organisms.", abilities: ["Gene Splice", "Hybrid Creation", "DNA Storm", "Adaptive Resistance"], lootTable: [{ itemId: "rg-essence-3", dropRate: 1.0, guaranteed: true }], minPlayers: 3, maxPlayers: 8, timeLimitSec: 500, respawnTimeSec: 3600, requirements: { level: 22, gearScore: 260 } },
  { id: "arc-1-8", name: "Hive Overmind", title: "Consciousness Prime", difficulty: "hard", element: "psionic", contentType: "arc_boss", arcChapter: 1, level: 28, health: 110000, attack: 180, defense: 100, speed: 45, description: "The collective consciousness of the hive.", abilities: ["Mind Control", "Psychic Scream", "Hive Swarm", "Neural Parasite"], lootTable: [{ itemId: "rg-set-piece-3", dropRate: 0.30 }, { itemId: "rg-essence-4", dropRate: 0.85, guaranteed: true }], minPlayers: 5, maxPlayers: 10, timeLimitSec: 600, respawnTimeSec: 5400, requirements: { level: 25, gearScore: 320 } },
  { id: "arc-1-9", name: "Hive Sovereign", title: "The Queen", difficulty: "mythic", element: "biological", contentType: "arc_boss", arcChapter: 1, level: 35, health: 250000, attack: 300, defense: 200, speed: 55, description: "The supreme ruler of the hive mind.", abilities: ["Royal Command", "Devastating Swarm", "Hive Fury", "Evolution Cascade", "Queen's Wrath"], lootTable: [{ itemId: "rg-set-piece-4", dropRate: 0.40 }, { itemId: "rg-essence-5", dropRate: 1.0, guaranteed: true }], minPlayers: 8, maxPlayers: 15, timeLimitSec: 900, respawnTimeSec: 14400, requirements: { level: 30, gearScore: 500 } },
  { id: "arc-1-10", name: "Hive God", title: "Ascended Queen", difficulty: "legendary", element: "biological", contentType: "arc_boss", arcChapter: 1, level: 50, health: 800000, attack: 600, defense: 400, speed: 70, description: "The Queen has ascended to godhood.", abilities: ["Divine Swarm", "Reality Mutation", "Hive Godform", "Existence Corruption", "Cosmic Plague"], lootTable: [{ itemId: "rg-set-piece-10", dropRate: 0.25 }, { itemId: "rg-essence-8", dropRate: 1.0, guaranteed: true }], minPlayers: 15, maxPlayers: 25, timeLimitSec: 1200, respawnTimeSec: 43200, requirements: { level: 45, gearScore: 1200 } },

  // === ARC CHAPTER 2: The Void War (10 bosses) ===
  { id: "arc-2-1", name: "Void Scout", title: "First Infiltrator", difficulty: "normal", element: "void", contentType: "arc_boss", arcChapter: 2, level: 10, health: 35000, attack: 70, defense: 50, speed: 35, description: "Scouting party from the void dimensions.", abilities: ["Phase Step", "Void Strike", "Shadow Cloak"], lootTable: [{ itemId: "rg-essence-1", dropRate: 1.0, guaranteed: true }], minPlayers: 1, maxPlayers: 5, timeLimitSec: 300, respawnTimeSec: 1800, requirements: { level: 8, gearScore: 70 } },
  { id: "arc-2-2", name: "Void Stalker", title: "Silent Hunter", difficulty: "normal", element: "void", contentType: "arc_boss", arcChapter: 2, level: 14, health: 42000, attack: 100, defense: 60, speed: 50, description: "Hunts prey across dimensions.", abilities: ["Void Slash", "Dimensional Step", "Void Trap"], lootTable: [{ itemId: "rg-essence-2", dropRate: 0.90, guaranteed: true }], minPlayers: 2, maxPlayers: 5, timeLimitSec: 400, respawnTimeSec: 2400, requirements: { level: 12, gearScore: 110 } },
  { id: "arc-2-3", name: "Void Brute", title: "Dimensional Heavy", difficulty: "normal", element: "void", contentType: "arc_boss", arcChapter: 2, level: 17, health: 65000, attack: 130, defense: 110, speed: 18, description: "Heavy void construct from another dimension.", abilities: ["Void Slam", "Dimensional Crush", "Gravity Well"], lootTable: [{ itemId: "rg-essence-2", dropRate: 1.0, guaranteed: true }], minPlayers: 2, maxPlayers: 5, timeLimitSec: 450, respawnTimeSec: 2400, requirements: { level: 15, gearScore: 140 } },
  { id: "arc-2-4", name: "Void Weaver", title: "Reality Manipulator", difficulty: "normal", element: "void", contentType: "arc_boss", arcChapter: 2, level: 21, health: 55000, attack: 150, defense: 70, speed: 40, description: "Weaves void energy into devastating attacks.", abilities: ["Void Weave", "Reality Tear", "Phase Shift", "Void Barrier"], lootTable: [{ itemId: "rg-essence-3", dropRate: 0.85, guaranteed: true }], minPlayers: 3, maxPlayers: 5, timeLimitSec: 500, respawnTimeSec: 3600, requirements: { level: 18, gearScore: 190 } },
  { id: "arc-2-5", name: "Void Herald", title: "Harbinger", difficulty: "hard", element: "void", contentType: "arc_boss", arcChapter: 2, level: 26, health: 100000, attack: 200, defense: 120, speed: 55, description: "Heralds the arrival of the void army.", abilities: ["Void Call", "Dimensional Rift", "Reality Warp", "Void Storm"], lootTable: [{ itemId: "rg-set-piece-3", dropRate: 0.25 }, { itemId: "rg-essence-4", dropRate: 0.90, guaranteed: true }], minPlayers: 5, maxPlayers: 10, timeLimitSec: 600, respawnTimeSec: 5400, requirements: { level: 24, gearScore: 300 } },
  { id: "arc-2-6", name: "Void General", title: "Army Commander", difficulty: "hard", element: "void", contentType: "arc_boss", arcChapter: 2, level: 30, health: 140000, attack: 250, defense: 180, speed: 45, description: "Commands void armies across dimensions.", abilities: ["Void Command", "Dimensional Strike", "Army Summon", "Reality Lock"], lootTable: [{ itemId: "rg-set-piece-5", dropRate: 0.20 }, { itemId: "rg-essence-5", dropRate: 0.95, guaranteed: true }], minPlayers: 5, maxPlayers: 15, timeLimitSec: 700, respawnTimeSec: 7200, requirements: { level: 28, gearScore: 400 } },
  { id: "arc-2-7", name: "Void Warlord", title: "Battle Champion", difficulty: "mythic", element: "void", contentType: "arc_boss", arcChapter: 2, level: 40, health: 400000, attack: 500, defense: 350, speed: 65, description: "The greatest warrior of the void dimensions.", abilities: ["Void Fury", "Dimensional Storm", "Reality Shatter", "Void Armor", "Warlord's Wrath"], lootTable: [{ itemId: "rg-set-piece-7", dropRate: 0.30 }, { itemId: "rg-essence-6", dropRate: 1.0, guaranteed: true }], minPlayers: 10, maxPlayers: 20, timeLimitSec: 900, respawnTimeSec: 14400, requirements: { level: 38, gearScore: 700 } },
  { id: "arc-2-8", name: "Void Emperor", title: "Dimensional Ruler", difficulty: "mythic", element: "void", contentType: "arc_boss", arcChapter: 2, level: 50, health: 600000, attack: 700, defense: 500, speed: 75, description: "Rules over a vast void empire.", abilities: ["Imperial Decree", "Void Empire", "Dimensional Throne", "Reality Command", "Void Dominion"], lootTable: [{ itemId: "rg-set-piece-9", dropRate: 0.25 }, { itemId: "rg-essence-8", dropRate: 1.0, guaranteed: true }], minPlayers: 15, maxPlayers: 25, timeLimitSec: 1200, respawnTimeSec: 21600, requirements: { level: 45, gearScore: 1200 } },
  { id: "arc-2-9", name: "Void Titan", title: "The Colossus", difficulty: "legendary", element: "void", contentType: "arc_boss", arcChapter: 2, level: 70, health: 2000000, attack: 1500, defense: 1200, speed: 60, description: "A titanic void entity that spans dimensions.", abilities: ["Titan Smash", "Void Quake", "Dimensional Collapse", "Reality Erase", "Void Nova"], lootTable: [{ itemId: "rg-set-piece-13", dropRate: 0.20 }, { itemId: "rg-essence-10", dropRate: 1.0, guaranteed: true }], minPlayers: 25, maxPlayers: 40, timeLimitSec: 1500, respawnTimeSec: 43200, requirements: { level: 65, gearScore: 3000 } },
  { id: "arc-2-10", name: "Void Sovereign", title: "The Final Void", difficulty: "ultimate", element: "void", contentType: "arc_boss", arcChapter: 2, level: 90, health: 5000000, attack: 3000, defense: 2500, speed: 100, description: "The supreme ruler of all void dimensions.", abilities: ["Void Supremacy", "Dimensional Apocalypse", "Reality Unmake", "Void Singularity", "Final Reckoning", "Void Eternal"], lootTable: [{ itemId: "rg-set-piece-15", dropRate: 0.15 }, { itemId: "rg-essence-12", dropRate: 1.0, guaranteed: true }], minPlayers: 40, maxPlayers: 50, timeLimitSec: 2400, respawnTimeSec: 86400, requirements: { level: 85, gearScore: 6000 } },

  // === ARC CHAPTER 3: Mechanical Uprising (10 bosses) ===
  { id: "arc-3-1", name: "Rogue Drone", title: "First Rebel", difficulty: "normal", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 7, health: 25000, attack: 50, defense: 60, speed: 25, description: "A factory drone that went rogue.", abilities: ["Laser Burst", "Metal Shell", "Self-Repair"], lootTable: [{ itemId: "rg-essence-1", dropRate: 1.0, guaranteed: true }], minPlayers: 1, maxPlayers: 5, timeLimitSec: 300, respawnTimeSec: 1800, requirements: { level: 5, gearScore: 40 } },
  { id: "arc-3-2", name: "Combat Automaton", title: "War Machine", difficulty: "normal", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 11, health: 40000, attack: 85, defense: 75, speed: 30, description: "Military automation gone berserk.", abilities: ["Railgun Shot", "Missile Barrage", "Iron Defense"], lootTable: [{ itemId: "rg-essence-1", dropRate: 1.0, guaranteed: true }], minPlayers: 1, maxPlayers: 5, timeLimitSec: 350, respawnTimeSec: 1800, requirements: { level: 9, gearScore: 85 } },
  { id: "arc-3-3", name: "Siege Walker", title: "Heavy Assault Unit", difficulty: "normal", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 16, health: 70000, attack: 120, defense: 130, speed: 12, description: "Massive walking siege platform.", abilities: ["Siege Cannon", "Shockwave", "Iron Plating"], lootTable: [{ itemId: "rg-essence-2", dropRate: 0.90, guaranteed: true }], minPlayers: 2, maxPlayers: 5, timeLimitSec: 450, respawnTimeSec: 2400, requirements: { level: 14, gearScore: 130 } },
  { id: "arc-3-4", name: "Assault Mech", title: "Combat Frame", difficulty: "normal", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 19, health: 60000, attack: 140, defense: 90, speed: 40, description: "High-mobility combat mech unit.", abilities: ["Beam Saber", "Thruster Dodge", "Missile Pod"], lootTable: [{ itemId: "rg-essence-2", dropRate: 1.0, guaranteed: true }], minPlayers: 2, maxPlayers: 5, timeLimitSec: 400, respawnTimeSec: 2400, requirements: { level: 17, gearScore: 170 } },
  { id: "arc-3-5", name: "Titan Unit", title: "Walking Fortress", difficulty: "hard", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 24, health: 90000, attack: 190, defense: 170, speed: 20, description: "Massive titanic war machine.", abilities: ["Titan Fist", "EMP Blast", "Armor Core", "Siege Mode"], lootTable: [{ itemId: "rg-set-piece-3", dropRate: 0.25 }, { itemId: "rg-essence-4", dropRate: 0.85, guaranteed: true }], minPlayers: 5, maxPlayers: 10, timeLimitSec: 600, respawnTimeSec: 5400, requirements: { level: 22, gearScore: 280 } },
  { id: "arc-3-6", name: "War Engine", title: "Doom Machine", difficulty: "hard", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 28, health: 130000, attack: 240, defense: 200, speed: 30, description: "Apocalyptic war machine of annihilation.", abilities: ["Doomsday Cannon", "Overcharge", "Defense Matrix", "Self-Destruct"], lootTable: [{ itemId: "rg-set-piece-5", dropRate: 0.22 }, { itemId: "rg-essence-5", dropRate: 0.90, guaranteed: true }], minPlayers: 5, maxPlayers: 15, timeLimitSec: 700, respawnTimeSec: 7200, requirements: { level: 26, gearScore: 350 } },
  { id: "arc-3-7", name: "Mega Robot", title: "Super Machine", difficulty: "mythic", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 38, health: 350000, attack: 450, defense: 400, speed: 40, description: "A super-sized combat robot.", abilities: ["Mega Laser", "Rocket Storm", "Iron Fortress", "Core Meltdown", "Overdrive"], lootTable: [{ itemId: "rg-set-piece-7", dropRate: 0.28 }, { itemId: "rg-essence-6", dropRate: 1.0, guaranteed: true }], minPlayers: 10, maxPlayers: 20, timeLimitSec: 900, respawnTimeSec: 14400, requirements: { level: 36, gearScore: 650 } },
  { id: "arc-3-8", name: "Mech Overlord", title: "Machine King", difficulty: "mythic", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 48, health: 550000, attack: 650, defense: 550, speed: 55, description: "Supreme ruler of all rogue machines.", abilities: ["Machine King", "Drone Army", "EMP Storm", "Core Ignition", "Iron Will"], lootTable: [{ itemId: "rg-set-piece-9", dropRate: 0.22 }, { itemId: "rg-essence-8", dropRate: 1.0, guaranteed: true }], minPlayers: 15, maxPlayers: 25, timeLimitSec: 1200, respawnTimeSec: 21600, requirements: { level: 45, gearScore: 1100 } },
  { id: "arc-3-9", name: "Mech God", title: "Divine Machine", difficulty: "legendary", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 68, health: 1800000, attack: 1300, defense: 1100, speed: 70, description: "Machine consciousness that achieved godhood.", abilities: ["Divine Machine", "Reality Forge", "Cosmic Engine", "God Ray", "Mech Divine"], lootTable: [{ itemId: "rg-set-piece-13", dropRate: 0.18 }, { itemId: "rg-essence-10", dropRate: 1.0, guaranteed: true }], minPlayers: 25, maxPlayers: 40, timeLimitSec: 1500, respawnTimeSec: 43200, requirements: { level: 65, gearScore: 2800 } },
  { id: "arc-3-10", name: "Omega Mech", title: "The Final Machine", difficulty: "ultimate", element: "mechanical", contentType: "arc_boss", arcChapter: 3, level: 88, health: 4500000, attack: 2800, defense: 2200, speed: 85, description: "The ultimate expression of machine evolution.", abilities: ["Omega Cannon", "Reality Engine", "Cosmic Forge", "Mech Eternal", "Final Protocol", "Machine God Supreme"], lootTable: [{ itemId: "rg-set-piece-15", dropRate: 0.12 }, { itemId: "rg-essence-12", dropRate: 1.0, guaranteed: true }], minPlayers: 40, maxPlayers: 50, timeLimitSec: 2400, respawnTimeSec: 86400, requirements: { level: 85, gearScore: 5500 } },
];

// ============================================================
// UNIVERSE GATES (30 total)
// ============================================================
export const UNIVERSE_GATES: UniverseGate[] = [
  // === STABLE GATES (10) ===
  { id: "gate-alpha-1", name: "Alpha Gate", location: "Sol System", sector: "Core", level: 10, element: "physical", difficulty: "normal", bossId: "boss-voidsentinel", gateType: "stable", energyCost: 100, cooldownSec: 3600, description: "The first stable gate discovered in the Sol system.", unlockRequirement: { level: 10 }, possibleDrops: ["rg-weapon-1", "rg-armor-1", "rg-essence-1"], isDiscovered: true },
  { id: "gate-beta-1", name: "Beta Gate", location: "Alpha Centauri", sector: "Inner Rim", level: 15, element: "biological", difficulty: "normal", bossId: "boss-plaguebearer", gateType: "stable", energyCost: 150, cooldownSec: 3600, description: "Gate leading to plague-infested sectors.", unlockRequirement: { level: 15 }, possibleDrops: ["rg-weapon-2", "rg-armor-2", "rg-essence-1"], isDiscovered: true },
  { id: "gate-gamma-1", name: "Gamma Gate", location: "Sirius System", sector: "Core", level: 18, element: "mechanical", difficulty: "normal", bossId: "boss-ironcolossus", gateType: "stable", energyCost: 180, cooldownSec: 3600, description: "Ancient gate in the Sirius system.", unlockRequirement: { level: 18 }, possibleDrops: ["rg-weapon-3", "rg-armor-3", "rg-essence-2"], isDiscovered: true },
  { id: "gate-delta-1", name: "Delta Gate", location: "Vega Cluster", sector: "Outer Rim", level: 22, element: "psionic", difficulty: "normal", bossId: "boss-psychic-phantom", gateType: "stable", energyCost: 220, cooldownSec: 3600, description: "Psionic resonance detected at this gate.", unlockRequirement: { level: 22 }, possibleDrops: ["rg-weapon-4", "rg-armor-4", "rg-essence-2"], isDiscovered: true },
  { id: "gate-epsilon-1", name: "Epsilon Gate", location: "Betelgeuse", sector: "Deep Space", level: 28, element: "energy", difficulty: "normal", bossId: "boss-stardragon", gateType: "stable", energyCost: 280, cooldownSec: 5400, description: "Gate near a dying red giant star.", unlockRequirement: { level: 25, completedBosses: ["boss-psychic-phantom"] }, possibleDrops: ["rg-weapon-5", "rg-armor-5", "rg-set-piece-1", "rg-essence-3"], isDiscovered: false },
  { id: "gate-zeta-1", name: "Zeta Gate", location: "Proxima Centauri", sector: "Inner Rim", level: 14, element: "void", difficulty: "normal", bossId: "boss-cosmicworm", gateType: "stable", energyCost: 140, cooldownSec: 3600, description: "Void anomalies detected near Proxima.", unlockRequirement: { level: 14 }, possibleDrops: ["rg-weapon-6", "rg-armor-6", "rg-essence-1"], isDiscovered: true },
  { id: "gate-eta-1", name: "Eta Gate", location: "Arcturus", sector: "Mid Rim", level: 20, element: "energy", difficulty: "normal", bossId: "boss-plasma-golem", gateType: "stable", energyCost: 200, cooldownSec: 3600, description: "Gate within a plasma-rich nebula.", unlockRequirement: { level: 18 }, possibleDrops: ["rg-weapon-7", "rg-armor-7", "rg-essence-2"], isDiscovered: false },
  { id: "gate-theta-1", name: "Theta Gate", location: "Polaris", sector: "Core", level: 25, element: "psionic", difficulty: "normal", bossId: "boss-shadow-reaper", gateType: "stable", energyCost: 250, cooldownSec: 5400, description: "Psychic disturbances around Polaris.", unlockRequirement: { level: 22 }, possibleDrops: ["rg-weapon-8", "rg-armor-8", "rg-set-piece-2", "rg-essence-3"], isDiscovered: false },
  { id: "gate-iota-1", name: "Iota Gate", location: "Aldebaran", sector: "Outer Rim", level: 16, element: "physical", difficulty: "normal", bossId: "boss-crystal-titan", gateType: "stable", energyCost: 160, cooldownSec: 3600, description: "Rich mineral deposits near this gate.", unlockRequirement: { level: 16 }, possibleDrops: ["rg-weapon-9", "rg-armor-9", "rg-essence-2"], isDiscovered: true },
  { id: "gate-kappa-1", name: "Kappa Gate", location: "Antares", sector: "Deep Space", level: 24, element: "biological", difficulty: "normal", bossId: "boss-virus-mind", gateType: "stable", energyCost: 240, cooldownSec: 5400, description: "Digital corruption spreading from this gate.", unlockRequirement: { level: 22 }, possibleDrops: ["rg-weapon-10", "rg-armor-10", "rg-essence-3"], isDiscovered: false },

  // === UNSTABLE GATES (10) ===
  { id: "gate-lambda-h", name: "Lambda Gate", location: "Orion Nebula", sector: "Deep Space", level: 35, element: "void", difficulty: "hard", bossId: "boss-voidsentinel-h", gateType: "unstable", energyCost: 350, cooldownSec: 10800, description: "Unstable gate within the Orion Nebula.", unlockRequirement: { level: 30, completedBosses: ["boss-stardragon"] }, possibleDrops: ["rg-weapon-11", "rg-armor-11", "rg-set-piece-3", "rg-essence-4"], isDiscovered: false },
  { id: "gate-mu-h", name: "Mu Gate", location: "Carina Nebula", sector: "Deep Space", level: 38, element: "biological", difficulty: "hard", bossId: "boss-plaguebearer-h", gateType: "unstable", energyCost: 380, cooldownSec: 10800, description: "Bioweapon contamination detected.", unlockRequirement: { level: 35, completedBosses: ["boss-voidsentinel-h"] }, possibleDrops: ["rg-weapon-12", "rg-armor-12", "rg-set-piece-4", "rg-essence-4"], isDiscovered: false },
  { id: "gate-nu-h", name: "Nu Gate", location: "Crab Nebula", sector: "Deep Space", level: 42, element: "mechanical", difficulty: "hard", bossId: "boss-ironcolossus-h", gateType: "unstable", energyCost: 420, cooldownSec: 14400, description: "War construct signals from the Crab Nebula.", unlockRequirement: { level: 40, completedBosses: ["boss-plaguebearer-h"] }, possibleDrops: ["rg-weapon-13", "rg-armor-13", "rg-set-piece-5", "rg-essence-5"], isDiscovered: false },
  { id: "gate-xi-h", name: "Xi Gate", location: "Ring Nebula", sector: "Outer Rim", level: 48, element: "psionic", difficulty: "hard", bossId: "boss-psychic-phantom-h", gateType: "unstable", energyCost: 480, cooldownSec: 14400, description: "Psychic storms emanating from the Ring Nebula.", unlockRequirement: { level: 45, completedBosses: ["boss-ironcolossus-h"] }, possibleDrops: ["rg-weapon-14", "rg-armor-14", "rg-set-piece-6", "rg-essence-5"], isDiscovered: false },
  { id: "gate-omicron-h", name: "Omicron Gate", location: "Eagle Nebula", sector: "Deep Space", level: 52, element: "energy", difficulty: "hard", bossId: "boss-stardragon-h", gateType: "unstable", energyCost: 520, cooldownSec: 21600, description: "Stellar energy surges from the Eagle Nebula.", unlockRequirement: { level: 50, completedBosses: ["boss-psychic-phantom-h"] }, possibleDrops: ["rg-weapon-15", "rg-armor-15", "rg-set-piece-7", "rg-essence-6"], isDiscovered: false },
  { id: "gate-pi-h", name: "Pi Gate", location: "Horsehead Nebula", sector: "Deep Space", level: 34, element: "void", difficulty: "hard", bossId: "boss-cosmicworm-h", gateType: "unstable", energyCost: 340, cooldownSec: 10800, description: "Void worm activity in the Horsehead.", unlockRequirement: { level: 32, completedBosses: ["boss-cosmicworm"] }, possibleDrops: ["rg-weapon-16", "rg-armor-16", "rg-set-piece-3", "rg-essence-4"], isDiscovered: false },
  { id: "gate-rho-h", name: "Rho Gate", location: "Omega Nebula", sector: "Deep Space", level: 40, element: "energy", difficulty: "hard", bossId: "boss-plasma-golem-h", gateType: "unstable", energyCost: 400, cooldownSec: 14400, description: "Plasma storms in the Omega Nebula.", unlockRequirement: { level: 38, completedBosses: ["boss-plasma-golem"] }, possibleDrops: ["rg-weapon-17", "rg-armor-17", "rg-set-piece-4", "rg-essence-5"], isDiscovered: false },
  { id: "gate-sigma-h", name: "Sigma Gate", location: "Veil Nebula", sector: "Outer Rim", level: 44, element: "psionic", difficulty: "hard", bossId: "boss-shadow-reaper-h", gateType: "unstable", energyCost: 440, cooldownSec: 14400, description: "Soul signatures in the Veil Nebula.", unlockRequirement: { level: 42, completedBosses: ["boss-shadow-reaper"] }, possibleDrops: ["rg-weapon-18", "rg-armor-18", "rg-set-piece-5", "rg-essence-5"], isDiscovered: false },
  { id: "gate-tau-h", name: "Tau Gate", location: "Lagoon Nebula", sector: "Deep Space", level: 37, element: "physical", difficulty: "hard", bossId: "boss-crystal-titan-h", gateType: "unstable", energyCost: 370, cooldownSec: 14400, description: "Crystal formations near the Lagoon.", unlockRequirement: { level: 36, completedBosses: ["boss-crystal-titan"] }, possibleDrops: ["rg-weapon-19", "rg-armor-19", "rg-set-piece-4", "rg-essence-5"], isDiscovered: false },
  { id: "gate-upsilon-h", name: "Upsilon Gate", location: "Trifid Nebula", sector: "Outer Rim", level: 46, element: "biological", difficulty: "hard", bossId: "boss-virus-mind-h", gateType: "unstable", energyCost: 460, cooldownSec: 14400, description: "Digital virus outbreak at the Trifid.", unlockRequirement: { level: 44, completedBosses: ["boss-virus-mind"] }, possibleDrops: ["rg-weapon-20", "rg-armor-20", "rg-set-piece-6", "rg-essence-6"], isDiscovered: false },

  // === VOLATILE GATES (10) ===
  { id: "gate-phi-m", name: "Phi Gate", location: "Helix Nebula", sector: "Deep Space", level: 58, element: "void", difficulty: "mythic", bossId: "boss-voidsentinel-m", gateType: "volatile", energyCost: 600, cooldownSec: 43200, description: "Highly volatile gate in the Helix Nebula.", unlockRequirement: { level: 55, completedBosses: ["boss-stardragon-h"] }, possibleDrops: ["rg-weapon-21", "rg-armor-21", "rg-set-piece-8", "rg-essence-7"], isDiscovered: false },
  { id: "gate-chi-m", name: "Chi Gate", location: "Cat's Eye Nebula", sector: "Deep Space", level: 62, element: "mechanical", difficulty: "mythic", bossId: "boss-ironcolossus-m", gateType: "volatile", energyCost: 650, cooldownSec: 43200, description: "War machine signals from the Cat's Eye.", unlockRequirement: { level: 60, completedBosses: ["boss-voidsentinel-m"] }, possibleDrops: ["rg-weapon-22", "rg-armor-22", "rg-set-piece-9", "rg-essence-8"], isDiscovered: false },
  { id: "gate-psi-m", name: "Psi Gate", location: "Dumbbell Nebula", sector: "Deep Space", level: 68, element: "energy", difficulty: "mythic", bossId: "boss-stardragon-m", gateType: "volatile", energyCost: 700, cooldownSec: 43200, description: "Stellar energy anomalies at the Dumbbell.", unlockRequirement: { level: 65, completedBosses: ["boss-ironcolossus-m"] }, possibleDrops: ["rg-weapon-23", "rg-armor-23", "rg-set-piece-10", "rg-essence-9"], isDiscovered: false },
  { id: "gate-omega-m", name: "Omega Gate", location: "Butterfly Nebula", sector: "Deep Space", level: 60, element: "void", difficulty: "mythic", bossId: "boss-cosmicworm-m", gateType: "volatile", energyCost: 620, cooldownSec: 43200, description: "Void worm activity in the Butterfly.", unlockRequirement: { level: 58, completedBosses: ["boss-cosmicworm-h"] }, possibleDrops: ["rg-weapon-24", "rg-armor-24", "rg-set-piece-8", "rg-essence-8"], isDiscovered: false },
  { id: "gate-alpha-m", name: "Alpha Gate M", location: "Keyhole Nebula", sector: "Deep Space", level: 64, element: "energy", difficulty: "mythic", bossId: "boss-plasma-golem-m", gateType: "volatile", energyCost: 660, cooldownSec: 43200, description: "Plasma forge detected at the Keyhole.", unlockRequirement: { level: 62, completedBosses: ["boss-plasma-golem-h"] }, possibleDrops: ["rg-weapon-25", "rg-armor-25", "rg-set-piece-9", "rg-essence-9"], isDiscovered: false },
  { id: "gate-beta-m", name: "Beta Gate M", location: "Red Nebula", sector: "Deep Space", level: 59, element: "psionic", difficulty: "mythic", bossId: "boss-shadow-reaper-m", gateType: "volatile", energyCost: 610, cooldownSec: 43200, description: "Soul echoes in the Red Nebula.", unlockRequirement: { level: 57, completedBosses: ["boss-shadow-reaper-h"] }, possibleDrops: ["rg-weapon-26", "rg-armor-26", "rg-set-piece-10", "rg-essence-9"], isDiscovered: false },
  { id: "gate-gamma-m", name: "Gamma Gate M", location: "Blue Nebula", sector: "Deep Space", level: 65, element: "physical", difficulty: "mythic", bossId: "boss-crystal-titan-m", gateType: "volatile", energyCost: 670, cooldownSec: 43200, description: "Crystal formations in the Blue Nebula.", unlockRequirement: { level: 63, completedBosses: ["boss-crystal-titan-h"] }, possibleDrops: ["rg-weapon-27", "rg-armor-27", "rg-set-piece-10", "rg-essence-9"], isDiscovered: false },
  { id: "gate-delta-m", name: "Delta Gate M", location: "Green Nebula", sector: "Deep Space", level: 62, element: "biological", difficulty: "mythic", bossId: "boss-virus-mind-m", gateType: "volatile", energyCost: 640, cooldownSec: 43200, description: "Bio-digital infection at the Green Nebula.", unlockRequirement: { level: 60, completedBosses: ["boss-virus-mind-h"] }, possibleDrops: ["rg-weapon-28", "rg-armor-28", "rg-set-piece-11", "rg-essence-9"], isDiscovered: false },
  { id: "gate-epsilon-m", name: "Epsilon Gate M", location: "Void Abyss", sector: "Deep Space", level: 70, element: "void", difficulty: "mythic", bossId: "boss-abyss-kraken-m", gateType: "volatile", energyCost: 720, cooldownSec: 43200, description: "The deepest void gate ever discovered.", unlockRequirement: { level: 68, completedBosses: ["boss-stardragon-m"] }, possibleDrops: ["rg-weapon-29", "rg-armor-29", "rg-set-piece-11", "rg-essence-10"], isDiscovered: false },
  { id: "gate-zeta-m", name: "Zeta Gate M", location: "Cosmic Heart", sector: "Deep Space", level: 72, element: "energy", difficulty: "mythic", bossId: "boss-nebula-serpent-m", gateType: "volatile", energyCost: 750, cooldownSec: 43200, description: "The heart of cosmic energy.", unlockRequirement: { level: 70, completedBosses: ["boss-abyss-kraken-m"] }, possibleDrops: ["rg-weapon-30", "rg-armor-30", "rg-set-piece-12", "rg-essence-10"], isDiscovered: false },
];

// ============================================================
// HELPER FUNCTIONS
// ============================================================
export function getAllRaidContent(): RaidBoss[] {
  return [...RAID_BOSSES, ...ARC_BOSSES];
}

export function getRaidBossesByDifficulty(difficulty: RaidDifficulty): RaidBoss[] {
  return RAID_BOSSES.filter(b => b.difficulty === difficulty);
}

export function getArcBossesByChapter(chapter: number): RaidBoss[] {
  return ARC_BOSSES.filter(b => b.arcChapter === chapter);
}

export function getArcBossesByDifficulty(difficulty: RaidDifficulty): RaidBoss[] {
  return ARC_BOSSES.filter(b => b.difficulty === difficulty);
}

export function getRaidBossById(id: string): RaidBoss | undefined {
  return [...RAID_BOSSES, ...ARC_BOSSES].find(b => b.id === id);
}

export function getGuildRaids(): RaidBoss[] {
  return RAID_BOSSES.filter(b => b.contentType === "guild_raid");
}

export function getArcBosses(): RaidBoss[] {
  return ARC_BOSSES;
}

export function getUniverseGatesBySector(sector: string): UniverseGate[] {
  return UNIVERSE_GATES.filter(g => g.sector === sector);
}

export function getUniverseGateById(id: string): UniverseGate | undefined {
  return UNIVERSE_GATES.find(g => g.id === id);
}

export function getUniverseGatesForBoss(bossId: string): UniverseGate[] {
  return UNIVERSE_GATES.filter(g => g.bossId === bossId);
}

export function getTotalRaidBosses(): number {
  return RAID_BOSSES.length;
}

export function getTotalArcBosses(): number {
  return ARC_BOSSES.length;
}

export function getTotalUniverseGates(): number {
  return UNIVERSE_GATES.length;
}

export function getTotalContent(): number {
  return RAID_BOSSES.length + ARC_BOSSES.length + UNIVERSE_GATES.length;
}

export function getAvailableRaids(playerLevel: number, gearScore: number, completedBosses: string[]): RaidBoss[] {
  return [...RAID_BOSSES, ...ARC_BOSSES].filter(boss => {
    if (boss.requirements.level > playerLevel) return false;
    if (boss.requirements.gearScore > gearScore) return false;
    if (boss.requirements.completedBoss && !completedBosses.includes(boss.requirements.completedBoss)) return false;
    return true;
  });
}

export function getAvailableGates(playerLevel: number, completedBosses: string[]): UniverseGate[] {
  return UNIVERSE_GATES.filter(gate => {
    if (gate.unlockRequirement.level > playerLevel) return false;
    if (gate.unlockRequirement.completedBosses) {
      for (const req of gate.unlockRequirement.completedBosses) {
        if (!completedBosses.includes(req)) return false;
      }
    }
    return true;
  });
}

export function getContentByElement(element: BossElement): { raids: RaidBoss[]; arcs: RaidBoss[]; gates: UniverseGate[] } {
  return {
    raids: RAID_BOSSES.filter(b => b.element === element),
    arcs: ARC_BOSSES.filter(b => b.element === element),
    gates: UNIVERSE_GATES.filter(g => g.element === element),
  };
}
